from __future__ import annotations

import enum
from datetime import datetime

from sqlalchemy import DateTime, Enum, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class NewsCategory(str, enum.Enum):
    TRANSACTION = "TRANSACTION"
    INJURY = "INJURY"
    GAME_RESULT = "GAME_RESULT"
    RUMOR = "RUMOR"
    QUOTE = "QUOTE"
    LEAGUE_NEWS = "LEAGUE_NEWS"
    DRAFT_NEWS = "DRAFT_NEWS"
    CONTROVERSY = "CONTROVERSY"
    NARRATIVE = "NARRATIVE"

class NewsItem(Base):
    """
    Represents a news article or headline in the 'Living World' feed.
    These are generated by the NarrativeEngine (Gemini) based on RPGEvents.
    """
    __tablename__ = "news_items"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    season_id: Mapped[int] = mapped_column(Integer, nullable=False)
    week: Mapped[int] = mapped_column(Integer, nullable=False)

    # Optional subjects
    team_id: Mapped[int | None] = mapped_column(Integer, ForeignKey("team.id"), nullable=True)
    player_id: Mapped[int | None] = mapped_column(Integer, ForeignKey("player.id"), nullable=True)

    category: Mapped[NewsCategory] = mapped_column(Enum(NewsCategory), nullable=False)
    headline: Mapped[str] = mapped_column(String, nullable=False)
    content: Mapped[str] = mapped_column(Text, nullable=False) # Gemini generated story

    image_url: Mapped[str | None] = mapped_column(String, nullable=True)

    # For sorting/filtering on the dashboard
    # 1.0 = Breaking News / Huge Story
    # 0.1 = Minor Note
    importance_score: Mapped[float] = mapped_column(Float, default=0.5)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<NewsItem(headline='{self.headline}', category='{self.category}')>"
