import enum

from sqlalchemy import JSON, Boolean, Column, ForeignKey, Integer, String
from sqlalchemy.orm import relationship

from app.models.base import Base


class Region(str, enum.Enum):
    NATIONAL = "NATIONAL"
    EAST = "EAST"
    SOUTH = "SOUTH"
    MIDWEST = "MIDWEST"
    WEST = "WEST"


class ScoutBias(str, enum.Enum):
    NEUTRAL = "NEUTRAL"
    OLD_SCHOOL = "OLD_SCHOOL"  # Overvalues Size/Strength
    ANALYTICS = "ANALYTICS"  # Overvalues Speed/Agility/Production
    CHARACTER = "CHARACTER"  # Overvalues Intangibles/Leadership
    RAS_LOVER = "RAS_LOVER"  # Overvalues Athleticism (RAS score)
    TECHNICIAN = "TECHNICIAN"  # Overvalues Skill/Technique


class Scout(Base):
    __tablename__ = "scouts"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String)

    # Relationships
    team_id = Column(Integer, ForeignKey("team.id"))
    team = relationship("Team", back_populates="scouts")

    # Attributes (0-100)
    evaluation_ability = Column(Integer, default=50)  # How close grade is to true rating
    efficiency = Column(Integer, default=50)  # How fast they generate reports
    reputation = Column(Integer, default=50)  # Affects salary/hiring cost

    # Specialty
    region = Column(String, default=Region.NATIONAL)
    bias = Column(String, default=ScoutBias.NEUTRAL)
    position_specialty = Column(String, nullable=True)  # e.g. "QB" or "OL"

    # Reports generated by this scout
    reports = relationship("ScoutingReport", back_populates="scout")


class ScoutingReport(Base):
    __tablename__ = "scouting_reports"

    id = Column(Integer, primary_key=True, index=True)

    # Links
    scout_id = Column(Integer, ForeignKey("scouts.id"))
    scout = relationship("Scout", back_populates="reports")

    player_id = Column(Integer, ForeignKey("player.id"))  # Prospect
    player = relationship("Player")

    season_id = Column(Integer, ForeignKey("season.id"))  # Which draft class

    # The Report Data
    # Instead of true 0-100, we store ranges or letter grades in JSON?
    # Or we store the "perceived" rating which might be off by +/- 15 points.

    perceived_overall = Column(Integer)  # The grade the scout GIVES (e.g. 78)
    confidence_score = Column(
        Integer, default=50
    )  # 0-100% confidence. Low confidence = wider range shown to user.

    # Detailed notes
    strengths = Column(JSON, default=list)
    weaknesses = Column(JSON, default=list)

    # Fog of War State
    is_unlocked = Column(Boolean, default=False)  # Has the user paid/waited to see this?
    tier_level = Column(Integer, default=1)  # 1=Basic, 2=Physicals, 3=Skills, 4=True Grade
