from __future__ import annotations

from datetime import datetime

from sqlalchemy import JSON, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class WeeklyRecap(Base):
    """
    Stores the 'SportsCenter' style weekly wrap-up generated by the AI.
    It summarizes the entire league's week, not just one team.
    """

    __tablename__ = "weekly_recaps"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    season_id: Mapped[int] = mapped_column(Integer, nullable=False)
    week: Mapped[int] = mapped_column(Integer, nullable=False)

    # Generated Narrative Summary
    # This acts as the script for the weekly show
    summary_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Key Highlights references
    mvp_player_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("player.id"), nullable=True
    )

    # ID of the most exciting play (for linking to highlight reel)
    play_of_the_week_id: Mapped[str | None] = mapped_column(String, nullable=True)

    # Description of an upset or shocker
    surprising_result: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Multimedia
    # List of image URLs or video links generated specifically for this recap
    media_assets: Mapped[list[str] | None] = mapped_column(JSON, nullable=True)

    # Meta
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"<WeeklyRecap(season={self.season_id}, week={self.week})>"
