"""
Agent Generator Service

Generates implementation plans from task lists using MCP infrastructure.
"""

import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class TaskItem:
    """Task item from Mission Control."""
    id: str
    note: str
    element_type: str
    screenshot_path: str | None = None
    has_research: bool = False


@dataclass
class GenerationResult:
    """Result of plan generation."""
    artifact_path: Path
    summary: str


class AgentGeneratorService:
    """
    Service for generating implementation plans from task lists.

    Uses MCP infrastructure for AI-powered plan generation.
    """

    def __init__(self, output_dir: Path | None = None):
        if output_dir is None:
            self.output_dir = Path.home() / ".gemini" / "antigravity" / "artifacts" / "implementation_plans"
        else:
            self.output_dir = output_dir

    def _ensure_directory(self) -> None:
        """Create output directory if it doesn't exist."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def _format_task_markdown(self, index: int, task: TaskItem) -> str:
        """Format a single task as markdown."""
        lines = [
            f"### Task {index}: {task.note[:80]}",
            f"- **Element Type**: `{task.element_type}`",
            f"- **Has AI Research**: {'✅ Yes' if task.has_research else '❌ No'}",
        ]

        if task.screenshot_path:
            lines.append(f"- **Screenshot**: [View]({task.screenshot_path})")

        lines.append("")
        return "\n".join(lines)

    def _generate_plan_content(self, tasks: list[TaskItem], context: str | None = None) -> str:
        """Generate the full implementation plan markdown."""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Header
        content = f"""# Implementation Plan

**Generated**: {timestamp}
**Total Tasks**: {len(tasks)}
"""

        if context:
            content += f"\n**Project Context**: {context}\n"

        content += """
---

## Overview

This implementation plan was generated from Mission Control task annotations.
Each task represents a UI improvement or feature request captured by the user.

---

## Tasks

"""

        # Add each task
        for i, task in enumerate(tasks, start=1):
            content += self._format_task_markdown(i, task)

        # Footer with implementation suggestions
        content += """
---

## Implementation Phases

### Phase 1: Quick Wins
Tasks that can be completed quickly with minimal dependencies.

*TBD - Analyze tasks for quick wins*

### Phase 2: Core Features
Main feature implementations that require more effort.

*TBD - Group related tasks*

### Phase 3: Polish & Testing
Final polish, edge cases, and testing.

*TBD - Add testing requirements*

---

## Notes

- Generated by Mission Control Agent Generator
- Review and prioritize tasks before implementation
- Update this plan as tasks are completed

"""
        return content

    async def generate_plan(
        self,
        tasks: list,
        project_context: str | None = None
    ) -> GenerationResult:
        """
        Generate an implementation plan from task items.

        Args:
            tasks: List of task items (Pydantic models or dicts)
            project_context: Optional context about the project

        Returns:
            GenerationResult with artifact path and summary
        """
        self._ensure_directory()

        # Convert to internal format
        task_items = []
        for t in tasks:
            if hasattr(t, 'id'):
                # Pydantic model
                task_items.append(TaskItem(
                    id=t.id,
                    note=t.note,
                    element_type=t.element_type,
                    screenshot_path=getattr(t, 'screenshot_path', None),
                    has_research=getattr(t, 'has_research', False)
                ))
            else:
                # Dict
                task_items.append(TaskItem(
                    id=t.get('id', ''),
                    note=t.get('note', ''),
                    element_type=t.get('element_type', 'Unknown'),
                    screenshot_path=t.get('screenshot_path'),
                    has_research=t.get('has_research', False)
                ))

        # Generate content
        content = self._generate_plan_content(task_items, project_context)

        # Generate filename
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"implementation_plan_{timestamp}.md"
        filepath = self.output_dir / filename

        # Write file
        filepath.write_text(content, encoding="utf-8")

        logger.info(f"Generated implementation plan: {filepath}")

        # Generate summary
        summary = f"Created implementation plan with {len(task_items)} tasks"

        return GenerationResult(
            artifact_path=filepath,
            summary=summary
        )


# Global instance
agent_generator = AgentGeneratorService()
