#!/usr/bin/env python3
"""
Artifact Generator Service
==========================
Generates timestamped markdown task list artifacts from annotations.

Context7 Best Practices:
- Pure functions for formatting
- Async I/O for file operations
- Clear type definitions
"""

import logging
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class AnnotationElement:
    """Element metadata from annotation."""

    selector: str
    tagName: str
    textContent: str | None = ""
    className: str | None = None


@dataclass
class AIResearchData:
    """AI research data for an annotation."""

    summary: str
    codeExamples: list[str]
    complexity: str
    sources: list[str]


@dataclass
class AnnotationData:
    """Full annotation data for artifact generation."""

    id: str
    timestamp: str
    note: str
    element: AnnotationElement
    aiResearch: AIResearchData | None = None


def format_annotation_markdown(index: int, annotation: AnnotationData) -> str:
    """
    Format a single annotation as markdown.

    Context7 Best Practice: Pure function for formatting.
    """
    # Use textContent or fall back to note for the title
    title_text = annotation.element.textContent or annotation.note
    title_text = title_text[:60] if title_text else "Untitled Task"

    lines = [
        f"### ☐ {index}. {title_text}",
        f"**Location**: `{annotation.element.selector}`",
        f"**Element**: `<{annotation.element.tagName}>`",
        f"**User Note**: {annotation.note}",
        "",
    ]

    if annotation.aiResearch:
        research = annotation.aiResearch
        lines.extend(
            [
                "**AI Research Summary**:",
                f"> {research.summary}",
                "",
                f"**Complexity**: {research.complexity}",
                "",
            ]
        )

        if research.codeExamples:
            lines.append("**Code Example**:")
            lines.append("```")
            lines.append(research.codeExamples[0])
            lines.append("```")
            lines.append("")

        if research.sources:
            lines.append(f"**Sources**: {', '.join(research.sources)}")
            lines.append("")

    lines.append("---")
    lines.append("")

    return "\n".join(lines)


def generate_artifact_content(annotations: list[AnnotationData]) -> str:
    """
    Generate the full markdown content for a task list artifact.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Header
    header = f"""# UI Improvement Task List
**Generated**: {timestamp}
**Total Items**: {len(annotations)}

---

## Tasks

"""

    # Format each annotation
    body_parts = []
    for i, annotation in enumerate(annotations, start=1):
        body_parts.append(format_annotation_markdown(i, annotation))

    # Footer
    footer = """
---

## Summary

| Priority | Count |
|----------|-------|
| Low      | TBD   |
| Medium   | TBD   |
| High     | TBD   |

*This task list was generated by the Visual UI Annotation System.*
"""

    return header + "\n".join(body_parts) + footer


class ArtifactGeneratorService:
    """
    Service for generating task list artifacts.
    """

    def __init__(self, output_dir: Path | None = None):
        if output_dir is None:
            # Default to .gemini artifacts directory
            self.output_dir = Path.home() / ".gemini" / "antigravity" / "artifacts" / "task_lists"
        else:
            self.output_dir = output_dir

    def _ensure_directory(self) -> None:
        """Create output directory if it doesn't exist."""
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_artifact(self, annotations: list[AnnotationData]) -> Path:
        """
        Generate a task list artifact from annotations.

        Args:
            annotations: List of annotation data

        Returns:
            Path to the generated artifact file
        """
        self._ensure_directory()

        # Generate filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"task_list_{timestamp}.md"
        filepath = self.output_dir / filename

        # Generate content
        content = generate_artifact_content(annotations)

        # Write file
        filepath.write_text(content, encoding="utf-8")

        logger.info(f"Generated task list artifact: {filepath}")
        return filepath

    async def generate_artifact_async(self, annotations: list[AnnotationData]) -> Path:
        """
        Async version of generate_artifact.
        """
        import asyncio

        return await asyncio.to_thread(self.generate_artifact, annotations)


# Global instance
artifact_generator = ArtifactGeneratorService()
