import json
import os
from pathlib import Path

REPO_ROOT = Path(r"c:\Users\cweir\OneDrive\Desktop\DevOps\THE-NFL-SIM-V2")
OUT_FILE = REPO_ROOT / ".agents" / "teamwork_preview_explorer_survey_fe" / "survey_frontend.md"

with open(REPO_ROOT / ".agents" / "teamwork_preview_explorer_survey_fe" / "full_catalog.json", "r", encoding="utf-8") as f:
    catalog = json.load(f)

with open(REPO_ROOT / ".agents" / "teamwork_preview_explorer_survey_fe" / "page_analysis.json", "r", encoding="utf-8") as f:
    page_analysis = json.load(f)

with open(REPO_ROOT / ".agents" / "teamwork_preview_explorer_survey_fe" / "audit_summary.json", "r", encoding="utf-8") as f:
    summary = json.load(f)

with open(REPO_ROOT / ".agents" / "teamwork_preview_explorer_survey_fe" / "unmounted_details.json", "r", encoding="utf-8") as f:
    unmounted_details = json.load(f)

mounted_comps = [c for c in catalog if c["status"] == "MOUNTED"]
unmounted_comps = [c for c in catalog if c["status"] != "MOUNTED"]

doc = []
doc.append("# Comprehensive Frontend Architecture & Component Survey")
doc.append("## NFL Sim Engine: The Digital Gridiron (THE-NFL-SIM-V2)")
doc.append(f"**Date:** 2026-08-23 | **Scope:** `frontend/src/` (Components, Pages, Loaders, Routing, Services, Types)")
doc.append("")
doc.append("---")
doc.append("")

doc.append("## 1. Executive Summary & Inventory Metrics")
doc.append("")
doc.append("| Metric | Count | Details |")
doc.append("|---|---|---|")
doc.append(f"| **Total Frontend TS/TSX Files** | 214 | Analyzed across components, pages, services, types, hooks, stores |")
doc.append(f"| **Total Page Views** | 18 | 15 actively routed in React Router v7, 3 unmounted legacy pages |")
doc.append(f"| **Total UI Components** | 129 | Located under `frontend/src/components/` and subdirectories |")
doc.append(f"| **Mounted Components** | {len(mounted_comps)} | Actively rendered in the route hierarchy |")
doc.append(f"| **Unmounted / Orphaned Components** | {len(unmounted_comps)} | Unreachable from `App.tsx` / `router.tsx` route tree |")
doc.append(f"| **Navigation Links** | 14 | Configured in sidebar `Navigation.tsx` |")
doc.append(f"| **Core 13 Views Coverage** | 13/13 (100%) | All 13 core views have active routing / page components |")
doc.append(f"| **Files with Mock / Fallback Data** | 16 | Identified across router loaders, services, and UI components |")
doc.append("")

doc.append("---")
doc.append("")
doc.append("## 2. The 13 Core Application Views: Mount & Route Matrix")
doc.append("The 13 mandatory application views specified in the architectural blueprint (`ORIGINAL_REQUEST.md`) are mapped below to their respective routes, page components, and mount status:")
doc.append("")
doc.append("| # | View Specification | Route Path(s) | Primary Page Component | Mounted Subcomponents | Mock / Placeholder Status |")
doc.append("|---|---|---|---|---|---|")
doc.append("| 1 | **Franchise War Room / Dynasty Hub** | `/`, `/dashboard` | `pages/Dashboard.tsx` | Inline Dashboard Cards, Theme Glow | Hardcoded opponent fallback on week transition |")
doc.append("| 2 | **Tactical Live Sim Chalkboard & Field Radar** | `/live-sim` | `pages/LiveSim.tsx` | `ScoreBoard`, `GameClock`, `FieldCanvas`, `PlayByPlayFeed`, `LiveGameVisualizer`, `GridironVisualizer`, `WeatherWidget`, `CoachingWidget`, `CrowdNoiseMeter` | Mock ball trajectory fallback in page & visualizer |")
doc.append("| 3 | **Offseason Draft Room & Scouting Fog of War** | `/offseason/draft`, `/draft` | `pages/DraftRoom.tsx` | `DraftBoard`, `DraftTicker`, `TradeModal`, `DraftAssistant`, `WarRoomTicker`, `TradePhone`, `ParallaxScene`, `BroadcastPanel` | `router.tsx` loader uses mock teams/picks fallback |")
doc.append("| 4 | **Coaching Dynasty Tree & Staff Matrix** | `/playbook` (Coaching Tree tab) | `pages/Playbook.tsx` | `CoachingTree`, `CoachingDynastyTree`, `GameplanDashboard`, `FamiliarityBar` | Mock familiarity formula for demo in GameplanDashboard |")
doc.append("| 5 | **Medical Trauma Center & Orthopedic Triage** | `/medical-center`, `/medical` | `pages/MedicalCenter.tsx` | `BodyMap`, `GenesisBiometricCard`, `FatigueMonitor`, `OrthopedicTriageModal` | Biometrics fallback defaults when loading |")
doc.append("| 6 | **Depth Chart & Positional Hierarchy** | `/empire/depth-chart`, `/depth-chart` | `pages/DepthChart.tsx` | `ChemistryBadge`, Framer Motion `Reorder` | Live endpoint `api.getTeamChemistry`, `api.updateDepthChart` |")
doc.append("| 7 | **Roster Management & Capology Contracts** | `/empire/front-office`, `/roster` | `pages/FrontOffice.tsx` | `DraggableCard`, `PlayerCard`, `CoachSettings`, `ArchetypeBadge` | Live endpoint `api.getTeamRoster`, `api.getTeam` |")
doc.append("| 8 | **Season Schedule & Week Simulator** | `/season` (Schedule tab), `/season-dashboard` | `pages/SeasonDashboard.tsx` | `ScheduleView`, `SeasonSummaryCard`, `QuickActions`, `NewsFeed` | Live endpoint `seasonApi.getSchedule`, `seasonApi.advanceWeek` |")
doc.append("| 9 | **League Standings & Playoff Bracket** | `/season` (Standings & Playoffs tabs) | `pages/SeasonDashboard.tsx` | `StandingsTable`, `PlayoffBracket`, `LeagueLeaders`, `PlayerModal` | Live endpoint `seasonApi.getStandings`, `seasonApi.getPlayoffBracket` |")
doc.append("| 10 | **Player Profile & Biometric/S2 Cognition Card** | `/players/:playerId/skills`, `/skills` | `pages/SkillsPage.tsx` | `SkillTreeCanvas`, `SkillsOverlay`, `AbilityUnlockTree`, `TraitBadgeGrid`, `ArchetypeBadge` | Unmounted `EnhancedPlayerProfile.tsx`; mock trait data in overlay |")
doc.append("| 11 | **Front Office GM Trades & Valuation Matrix** | `/empire/trade-center`, `/trades` | `pages/TradeCenterPage.tsx` | `TradeNegotiator`, `TradeBlock`, `PendingOffers`, `DroppableZone`, `DraggableAsset`, `TradeAnalyzer` | `tradeApi.ts` has mock fallback generators for offers |")
doc.append("| 12 | **Cryptographic Replay Telemetry** | `/live-sim` (3D/2D Telemetry) | `pages/LiveSim.tsx` | `LiveGameVisualizer`, `FieldCanvas`, `GridironVisualizer` | Replay scrubber and animator exist in codebase but are unmounted |")
doc.append("| 13 | **League Settings & Weather Simulation Config** | `/settings` | `pages/Settings.tsx` | Form controls connected to `useSettingsStore` | Persisted to localStorage / Zustand store |")
doc.append("")

doc.append("---")
doc.append("")
doc.append("## 3. Application Shell & Route Mount Hierarchy")
doc.append("")
doc.append("```text")
doc.append("App.tsx")
doc.append("└── RouterProvider (router.tsx)")
doc.append("    └── MainLayout.tsx")
doc.append("        ├── components/Navigation.tsx (Fixed 14-link Sidebar)")
doc.append("        ├── components/common/FeedbackWidget.tsx")
doc.append("        │   ├── AnnotationPopover.tsx")
doc.append("        │   ├── ElementInspector.tsx")
doc.append("        │   ├── RegionSelector.tsx")
doc.append("        │   ├── ScreenshotEditor.tsx")
doc.append("        │   └── TaskListPanel.tsx")
doc.append("        ├── components/audio/SoundtrackPlayer.tsx")
doc.append("        └── Outlet (Active Route View)")
doc.append("            ├── Route: /                     -> Dashboard.tsx")
doc.append("            ├── Route: /season               -> SeasonDashboard.tsx")
doc.append("            │   ├── ParallaxScene.tsx")
doc.append("            │   ├── RibbonTicker.tsx")
doc.append("            │   ├── BroadcastPanel.tsx")
doc.append("            │   ├── SeasonSummaryCard.tsx -> QuickActions.tsx")
doc.append("            │   ├── StandingsTable.tsx")
doc.append("            │   ├── ScheduleView.tsx")
doc.append("            │   ├── PlayoffBracket.tsx")
doc.append("            │   ├── LeagueLeaders.tsx -> PlayerModal.tsx")
doc.append("            │   └── NewsFeed.tsx")
doc.append("            ├── Route: /offseason            -> OffseasonDashboard.tsx")
doc.append("            │   ├── ParallaxScene.tsx")
doc.append("            │   ├── BroadcastPanel.tsx")
doc.append("            │   ├── OffseasonTimeline.tsx")
doc.append("            │   ├── SalaryCapWidget.tsx")
doc.append("            │   ├── TeamNeeds.tsx")
doc.append("            │   ├── DraftBoard.tsx")
doc.append("            │   │   ├── ScoutIntelligenceLens.tsx")
doc.append("            │   │   ├── GenesisReveal.tsx")
doc.append("            │   │   ├── GpsSpeedViz.tsx")
doc.append("            │   │   └── ScoutingReportModal.tsx")
doc.append("            │   ├── PlayerProgression.tsx")
doc.append("            │   └── NewsFeed.tsx")
doc.append("            ├── Route: /offseason/draft       -> DraftRoom.tsx")
doc.append("            │   ├── ParallaxScene.tsx")
doc.append("            │   ├── RibbonTicker.tsx")
doc.append("            │   ├── BroadcastPanel.tsx")
doc.append("            │   ├── DraftAssistant.tsx -> FeedbackCollector.tsx")
doc.append("            │   ├── WarRoomTicker.tsx")
doc.append("            │   ├── TradePhone.tsx")
doc.append("            │   ├── DraftBoard.tsx (with Scout Lens, Genesis Reveal, GPS Speed Viz)")
doc.append("            │   ├── DraftTicker.tsx")
doc.append("            │   └── TradeModal.tsx -> TradeAnalyzer.tsx")
doc.append("            ├── Route: /empire/front-office  -> FrontOffice.tsx")
doc.append("            │   ├── DraggableCard.tsx -> PlayerCard.tsx -> ArchetypeBadge.tsx, PlayerBackstoryModal.tsx")
doc.append("            │   └── CoachSettings.tsx -> Card.tsx")
doc.append("            ├── Route: /empire/depth-chart   -> DepthChart.tsx")
doc.append("            │   └── ChemistryBadge.tsx")
doc.append("            ├── Route: /empire/trade-center  -> TradeCenterPage.tsx")
doc.append("            │   ├── TradeNegotiator.tsx")
doc.append("            │   │   ├── DroppableZone.tsx -> DraggableAsset.tsx")
doc.append("            │   │   ├── TradeAnalyzer.tsx -> FeedbackCollector.tsx")
doc.append("            │   │   └── DraggableAsset.tsx")
doc.append("            │   ├── TradeBlock.tsx")
doc.append("            │   └── PendingOffers.tsx")
doc.append("            ├── Route: /empire/trophy-room   -> TrophyRoom.tsx")
doc.append("            │   └── TrophyCaseScene.tsx -> TrophyAssets.tsx (Lombardi, MVP, Division trophies)")
doc.append("            ├── Route: /live-sim             -> LiveSim.tsx")
doc.append("            │   ├── ScoreBoard.tsx -> MomentumIndicator.tsx")
doc.append("            │   ├── GameClock.tsx")
doc.append("            │   ├── FieldCanvas.tsx -> GameCanvas.tsx, PlayerSprite.tsx")
doc.append("            │   ├── PlayByPlayFeed.tsx -> InteractionTimeline.tsx -> InteractionBadge.tsx")
doc.append("            │   ├── PhysicsDebugOverlay.tsx -> FieldCanvas.tsx")
doc.append("            │   ├── WeatherWidget.tsx")
doc.append("            │   ├── GameStats.tsx")
doc.append("            │   ├── CoachingWidget.tsx -> Card.tsx")
doc.append("            │   ├── MomentumIndicator.tsx")
doc.append("            │   ├── CrowdNoiseMeter.tsx")
doc.append("            │   ├── GridironVisualizer.tsx")
doc.append("            │   └── LiveGameVisualizer.tsx -> EnhancedFieldVisualizer.tsx, EnhancedPlayerCharacter.tsx")
doc.append("            ├── Route: /medical-center       -> MedicalCenter.tsx")
doc.append("            │   ├── BodyMap.tsx")
doc.append("            │   ├── GenesisBiometricCard.tsx")
doc.append("            │   ├── FatigueMonitor.tsx")
doc.append("            │   └── OrthopedicTriageModal.tsx")
doc.append("            ├── Route: /playbook             -> Playbook.tsx")
doc.append("            │   ├── GameplanDashboard.tsx -> FamiliarityBar.tsx")
doc.append("            │   ├── CoachingTree.tsx -> CoachingDynastyTree.tsx")
doc.append("            │   └── Telestrator.tsx")
doc.append("            ├── Route: /training             -> TrainingCenter.tsx")
doc.append("            │   ├── StarfieldBackground.tsx")
doc.append("            │   ├── DrillSelector.tsx -> DrillCard3D.tsx")
doc.append("            │   ├── CoachingStyleDial.tsx")
doc.append("            │   ├── WeeklyScheduleTimeline.tsx")
doc.append("            │   └── TrainingSessionResult.tsx")
doc.append("            ├── Route: /skills               -> SkillsPage.tsx")
doc.append("            │   ├── SkillTreeCanvas.tsx -> SkillNode3D.tsx, ConnectionLine.tsx, StarfieldBackground.tsx")
doc.append("            │   ├── SkillsOverlay.tsx")
doc.append("            │   ├── AbilityUnlockTree.tsx")
doc.append("            │   ├── TraitBadgeGrid.tsx")
doc.append("            │   └── ArchetypeBadge.tsx")
doc.append("            ├── Route: /team-selection       -> TeamSelection.tsx")
doc.append("            │   ├── ParallaxScene.tsx")
doc.append("            │   ├── TiltCard.tsx")
doc.append("            │   └── RibbonTicker.tsx")
doc.append("            ├── Route: /settings             -> Settings.tsx")
doc.append("            └── Catch-all: *                 -> NotFound.tsx")
doc.append("```")
doc.append("")

doc.append("---")
doc.append("")
doc.append("## 4. Deep Catalog of All 129 Components")
doc.append("")

# Group catalog by subfolder
by_folder = {}
for item in catalog:
    parts = item["file_path"].split('/')
    folder = parts[2] if len(parts) > 3 else "root"
    if folder not in by_folder:
        by_folder[folder] = []
    by_folder[folder].append(item)

for folder, items in sorted(by_folder.items()):
    doc.append(f"### 4.{list(by_folder.keys()).index(folder)+1} Folder: `components/{folder}/` ({len(items)} Components)")
    doc.append("")
    for it in sorted(items, key=lambda x: x["component_name"]):
        st = "🟢 MOUNTED" if it["status"] == "MOUNTED" else "🔴 UNMOUNTED / ORPHANED"
        doc.append(f"#### `{it['component_name']}` ({it['file_path']}) — {st}")
        doc.append(f"- **Mount Status:** `{it['status']}`")
        if it["mounted_on"]:
            doc.append(f"- **Mounted In (Parent Files):** {', '.join(['`' + m + '`' for m in it['mounted_on']])}")
        if it["callers"]:
            doc.append(f"- **JSX Rendered By:** {', '.join(['`' + c + '`' for c in it['callers']])}")
        
        doc.append("- **Expected Props Interface:**")
        if it["expected_props"]:
            doc.append("  ```typescript")
            for prop in it["expected_props"]:
                doc.append(f"  {prop}")
            doc.append("  ```")
        else:
            doc.append("  *No required props (standalone / context consumer)*")

        if it["passed_props_samples"]:
            doc.append("- **Sample Props Passed at Call Site:**")
            for s in it["passed_props_samples"]:
                doc.append(f"  - In `{s['caller']}`: passed attributes `[{', '.join(s['passed_attrs'])}]`")

        if it["mock_hits"]:
            doc.append("- ⚠️ **Mock Data / Fallback Hits:**")
            for mh in it["mock_hits"]:
                doc.append(f"  - Line {mh[0]}: `{mh[1]}`")
        doc.append("")

doc.append("---")
doc.append("")
doc.append("## 5. Catalog of Unmounted & Orphaned Components (36 Components + 3 Legacy Pages)")
doc.append("The following components exist in the repository but have 0 incoming render calls in the active application tree:")
doc.append("")
doc.append("| Component Name | File Path | Original Purpose & Why Orphaned | Remediation Recommendation |")
doc.append("|---|---|---|---|")
doc.append("| `DraftLegacy` | `frontend/src/pages/DraftLegacy.tsx` | Old table-based draft room | Safe to archive / remove |")
doc.append("| `FrontOffice_Baseline` | `frontend/src/pages/FrontOffice_Baseline.tsx` | Static baseline roster screen | Retain for visual baseline tests or archive |")
doc.append("| `SeasonDashboardLegacy` | `frontend/src/pages/SeasonDashboardLegacy.tsx` | Early season dashboard prototype | Safe to archive / remove |")
doc.append("| `FieldVisualizer` | `frontend/src/components/3d/FieldVisualizer.tsx` | Early Three.js field renderer | Superseded by `EnhancedFieldVisualizer.tsx` |")
doc.append("| `PlayAnimator` | `frontend/src/components/3d/PlayAnimator.tsx` | 3D play trajectory animator | Integrate into `LiveGameVisualizer.tsx` for replay mode |")
doc.append("| `PlayerCharacter` | `frontend/src/components/3d/PlayerCharacter.tsx` | Early player 3D mesh | Superseded by `EnhancedPlayerCharacter.tsx` |")
doc.append("| `SceneContainer` | `frontend/src/components/3d/SceneContainer.tsx` | Canvas wrapper for early 3D view | Superseded by `LiveGameVisualizer.tsx` |")
doc.append("| `ErrorBoundary` | `frontend/src/components/ErrorBoundary.tsx` | Generic class error boundary | Router uses `RootErrorBoundary` and `RouteErrorBoundary` |")
doc.append("| `FieldView` | `frontend/src/components/FieldView.tsx` | Phase 1 static 2D formation diagram | Superseded by `FieldCanvas.tsx` & `GridironVisualizer.tsx` |")
doc.append("| `CoachCard` | `frontend/src/components/coaching/CoachCard.tsx` | Styled-component coach profile card | Mount inside `CoachSettings.tsx` or `CoachingTree.tsx` |")
doc.append("| `CoachingUnlockPanel` | `frontend/src/components/coaching/CoachingUnlockPanel.tsx` | Modal to unlock traits with coaching points | Mount in `CoachingTree.tsx` or `SkillsPage.tsx` |")
doc.append("| `NewsFeed` | `frontend/src/components/common/NewsFeed.tsx` | Standalone category-filtered news feed | Deduplicate with `components/season/NewsFeed.tsx` |")
doc.append("| `TraitBadge` | `frontend/src/components/common/TraitBadge.tsx` | Badge atom for player traits with tooltip | Deduplicate with `components/skills/TraitBadgeGrid.tsx` |")
doc.append("| `TraitTooltip` | `frontend/src/components/common/TraitTooltip.tsx` | Tooltip popup for trait tier details | Deduplicate with skills tooltip |")
doc.append("| `TraitManager` | `frontend/src/components/dev/TraitManager.tsx` | Dev panel to manually assign/remove traits | Mount as dev modal in `Settings.tsx` or `SkillsPage.tsx` |")
doc.append("| `FatigueIndicator` | `frontend/src/components/game/FatigueIndicator.tsx` | Circular energy/fatigue gauge | Integrate into `GameStats.tsx` / `ScoreBoard.tsx` in `LiveSim.tsx` |")
doc.append("| `ReplayScrubber` | `frontend/src/components/game/ReplayScrubber.tsx` | Play scrubber timeline for canvas replay | Mount below `FieldCanvas.tsx` in `LiveSim.tsx` |")
doc.append("| `LogoTimeline` | `frontend/src/components/history/LogoTimeline.tsx` | Historical franchise era logos | Mount inside `TrophyRoom.tsx` or `TeamSelection.tsx` |")
doc.append("| `SpotlightButton` | `frontend/src/components/immersive/SpotlightButton.tsx` | Radial cursor glow motion button atom | Reusable button atom; integrate into War Room buttons |")
doc.append("| `TreatmentModal` | `frontend/src/components/medical/TreatmentModal.tsx` | Modal for selecting 4 injury treatments | Mount inside `MedicalCenter.tsx` on body part click |")
doc.append("| `NewsFeedWidget` | `frontend/src/components/news/NewsFeedWidget.tsx` | Sidebar widget for living news | Mount in `Dashboard.tsx` or `SeasonDashboard.tsx` sidebar |")
doc.append("| `StorylineTracker` | `frontend/src/components/news/StorylineTracker.tsx` | Multi-week narrative arc tracker | Mount in `Dashboard.tsx` or `SeasonDashboard.tsx` |")
doc.append("| `WeeklyRecapModal` | `frontend/src/components/news/WeeklyRecapModal.tsx` | Modal summarizing completed week games | Mount in `SeasonDashboard.tsx` post-simulation |")
doc.append("| `news/index.ts` | `frontend/src/components/news/index.ts` | Barrel export for news components | Unreferenced barrel |")
doc.append("| `TraitBadge` | `frontend/src/components/shared/TraitBadge.tsx` | Duplicate shared trait badge | Deduplicate / merge |")
doc.append("| `TradeCenter` | `frontend/src/components/trades/TradeCenter.tsx` | Monolithic trade room container | Refactored into `TradeCenterPage.tsx` subcomponents |")
doc.append("| `trades/index.ts` | `frontend/src/components/trades/index.ts` | Barrel export for trade components | Unreferenced barrel |")
doc.append("| `CampSchedulePlanner` | `frontend/src/components/training/CampSchedulePlanner.tsx`| Training schedule calendar planner | Mount inside `TrainingCenter.tsx` |")
doc.append("| `CoachingStylePicker` | `frontend/src/components/training/CoachingStylePicker.tsx`| Card-based coaching style picker | Superseded by 3D `CoachingStyleDial.tsx` |")
doc.append("| `DrillCard` | `frontend/src/components/training/DrillCard.tsx` | 2D drill card item | Superseded by `DrillCard3D.tsx` |")
doc.append("| `PlayerProgressChart` | `frontend/src/components/training/PlayerProgressChart.tsx`| Progress line chart for training gains | Mount in `TrainingCenter.tsx` after session results |")
doc.append("| `PageTransition` | `frontend/src/components/transitions/PageTransition.tsx` | Wrapper for animated route transitions | `MainLayout.tsx` handles transitions directly |")
doc.append("| `transitions/index.ts` | `frontend/src/components/transitions/index.ts` | Barrel export for transitions | Unreferenced barrel |")
doc.append("| `transitionVariants.ts`| `frontend/src/components/transitions/transitionVariants.ts`| Framer motion variant definitions | Merged into `styles/motion.ts` |")
doc.append("| `Badge` | `frontend/src/components/ui/Badge.tsx` | Atom badge component | Reusable atom |")
doc.append("| `EnhancedPlayerProfile`| `frontend/src/components/ui/EnhancedPlayerProfile.tsx` | Tabbed full-card player modal | Mount on player click in `FrontOffice.tsx` / `DepthChart.tsx` |")
doc.append("| `PrimeCard` | `frontend/src/components/ui/PrimeCard.tsx` | Neon bordered card container | Reusable container |")
doc.append("| `Sidebar` | `frontend/src/components/ui/Sidebar.tsx` | Early sidebar navigation prototype | Superseded by `components/Navigation.tsx` |")
doc.append("| `TraitNotification` | `frontend/src/components/ui/TraitNotification.tsx` | Floating toast for unlocked traits | Mount in `MainLayout.tsx` or `SkillsPage.tsx` |")
doc.append("")

doc.append("---")
doc.append("")
doc.append("## 6. Comprehensive Mock & Fallback Data Audit")
doc.append("")
doc.append("### 6.1 Services Layer Mock Data")
doc.append("1. **`frontend/src/services/scouting.ts`**")
doc.append("   - `MOCK_SCOUTING_REPORT`: Hardcoded scouting report object containing traits, college stats, and physical ratings.")
doc.append("   - `MOCK_BACKSHIORY`: Hardcoded player backstory narrative.")
doc.append("   - **Remediation:** Wire `getScoutingReport(prospectId)` and `getPlayerBackstory(prospectId)` to FastAPI backend `/api/draft/prospects/{id}/report` and `/api/draft/prospects/{id}/backstory`.")
doc.append("")
doc.append("2. **`frontend/src/services/tradeApi.ts`**")
doc.append("   - `generateMockIncomingOffers(teamId)`: Procedurally generates synthetic trade offers when API fails.")
doc.append("   - `respondToOffer()`: Contains mock fallback simulation of offer acceptance/rejection.")
doc.append("   - `getTradeBlock()`: Falls back to mock tradeable assets if endpoint fails.")
doc.append("   - **Remediation:** Ensure backend `/api/trades/offers` and `/api/trades/respond` endpoints are fully implemented and remove client mock generators.")
doc.append("")
doc.append("3. **`frontend/src/services/ImageGenService.ts`**")
doc.append("   - `mockImages`: Array of 5 unsplash stock photos returned as random mock images.")
doc.append("   - **Remediation:** Wire to backend generative image endpoint or SVG avatar generator.")
doc.append("")
doc.append("### 6.2 Router Loaders Mock Data")
doc.append("1. **`frontend/src/router.tsx` (`draftRoomLoader`)**")
doc.append("   - Lines 148-205: Defines `mockTeams`, `mockSeason`, and `mockCurrentPick` directly in the loader.")
doc.append("   - **Remediation:** Replace mock loader data with live `api.getTeams()`, `seasonApi.getCurrentSeason()`, and `seasonApi.getCurrentPick()` calls.")
doc.append("")
doc.append("### 6.3 Components & Pages Inline Mock / Fallback Logic")
doc.append("1. **`pages/Dashboard.tsx` (Line 89)**: Calculates a simulated opponent string based on current week number instead of querying backend match schedule.")
doc.append("2. **`pages/LiveSim.tsx` (Line 64)**: Uses mock ball trajectory formula when websocket or simulation physics data is pending.")
doc.append("3. **`components/3d/LiveGameVisualizer.tsx` (Lines 116-126)**: Inlines `mockPlayResult` object with hardcoded yards gained and outcome.")
doc.append("4. **`components/coaching/GameplanDashboard.tsx` (Lines 47, 87)**: Uses hardcoded familiarity percentages (`85%`, `70%`) for offensive and defensive scheme execution.")
doc.append("5. **`components/game/FieldCanvas.tsx` (Line 205)**: Distinguishes offense vs defense by checking `player_id < 11`.")
doc.append("6. **`components/skills/SkillTreeCanvas.tsx` (Line 89)**: Defaults tier to `GOLD` for visual demonstration.")
doc.append("7. **`components/skills/SkillsOverlay.tsx` (Line 83)**: Inlines static perk description text.")
doc.append("8. **`components/history/LogoTimeline.tsx` (Line 5)**: Inlines `MOCK_HISTORY` array with 3 static era descriptions.")
doc.append("")

doc.append("---")
doc.append("")
doc.append("## 7. Navigation Completeness & View Gap Analysis")
doc.append("")
doc.append("### 7.1 Sidebar Navigation Coverage")
doc.append("`components/Navigation.tsx` exposes 14 navigation links:")
doc.append("1. `WAR ROOM` (`/`) -> `Dashboard.tsx`")
doc.append("2. `SEASON` (`/season`) -> `SeasonDashboard.tsx`")
doc.append("3. `ROSTER` (`/empire/front-office`) -> `FrontOffice.tsx`")
doc.append("4. `DEPTH CHART` (`/empire/depth-chart`) -> `DepthChart.tsx`")
doc.append("5. `PLAYBOOK` (`/playbook`) -> `Playbook.tsx`")
doc.append("6. `GAME DAY` (`/live-sim`) -> `LiveSim.tsx`")
doc.append("7. `MEDICAL` (`/medical-center`) -> `MedicalCenter.tsx`")
doc.append("8. `TRADE DESK` (`/empire/trade-center`) -> `TradeCenterPage.tsx`")
doc.append("9. `OFFSEASON` (`/offseason`) -> `OffseasonDashboard.tsx`")
doc.append("10. `DRAFT ROOM` (`/offseason/draft`) -> `DraftRoom.tsx`")
doc.append("11. `TROPHY ROOM` (`/empire/trophy-room`) -> `TrophyRoom.tsx`")
doc.append("12. `TRAINING` (`/training`) -> `TrainingCenter.tsx`")
doc.append("13. `MY FRANCHISE` (`/team-selection`) -> `TeamSelection.tsx`")
doc.append("14. `SETTINGS` (`/settings`) -> `Settings.tsx`")
doc.append("")
doc.append("### 7.2 Routing & Navigation Gaps Identified")
doc.append("1. **Skills Tree Page Discovery:** `SkillsPage.tsx` is mounted at `/players/:playerId/skills` and `/skills`, but lacks a direct menu entry in `Navigation.tsx`. Users currently navigate via player cards, but a standalone 'SKILLS & TRAITS' link or direct player profile modal transition is recommended.")
doc.append("2. **Player Detail Modal Integration:** `EnhancedPlayerProfile.tsx` provides a high-fidelity tabbed profile (Attributes, Contracts, Traits, Injury History) but is unmounted. `FrontOffice.tsx` and `DepthChart.tsx` currently only show basic cards or open player modals with partial data.")
doc.append("3. **Medical Treatment Action:** `MedicalCenter.tsx` displays `OrthopedicTriageModal.tsx`, while `TreatmentModal.tsx` contains 4 specific surgical/injection treatment pathways. Merging or mounting `TreatmentModal.tsx` on body part triage unlocks the 5-pathway orthopedic triage requirement.")
doc.append("4. **Live Replay Scrubber:** `ReplayScrubber.tsx` exists and controls `FieldCanvasRef`, but is unmounted in `LiveSim.tsx`. Mounting it enables instant replay and telemetry scrubbing.")
doc.append("5. **Living World News & Storylines:** `NewsFeedWidget.tsx` and `StorylineTracker.tsx` in `components/news/` are unmounted. Integrating them into `Dashboard.tsx` and `SeasonDashboard.tsx` activates emergent storyline tracking.")
doc.append("")

doc.append("---")
doc.append("")
doc.append("## 8. Prioritized Remediation Action Plan")
doc.append("")
doc.append("### Phase 1: High-Priority UI Component Mounts")
doc.append("1. **Mount `ReplayScrubber.tsx` into `LiveSim.tsx`** to fulfill cryptographic replay telemetry verification.")
doc.append("2. **Mount `TreatmentModal.tsx` into `MedicalCenter.tsx`** to fulfill the 5-pathway orthopedic triage requirement.")
doc.append("3. **Mount `EnhancedPlayerProfile.tsx` in `FrontOffice.tsx` and `DepthChart.tsx`** when clicking any player row or card.")
doc.append("4. **Mount `NewsFeedWidget.tsx` / `StorylineTracker.tsx` in `Dashboard.tsx`** for live franchise narrative generation.")
doc.append("5. **Mount `LogoTimeline.tsx` in `TrophyRoom.tsx`** to display franchise championship history.")
doc.append("")
doc.append("### Phase 2: Live Backend Endpoint Wiring & Mock Data Elimination")
doc.append("1. Replace `router.tsx` `draftRoomLoader` mock objects with live API fetches.")
doc.append("2. Wire `services/scouting.ts` to backend `/api/draft/prospects/{id}/report` and backstory endpoints.")
doc.append("3. Wire `services/tradeApi.ts` to live trade evaluation and incoming offers endpoints, eliminating `generateMockIncomingOffers()`.")
doc.append("4. Replace hardcoded familiarity calculations in `GameplanDashboard.tsx` with coach scheme ratings from backend.")
doc.append("")
doc.append("### Phase 3: Dead Code & Orphan Cleanup")
doc.append("1. Safely remove or archive legacy prototypes (`DraftLegacy.tsx`, `FrontOffice_Baseline.tsx`, `SeasonDashboardLegacy.tsx`, `FieldView.tsx`, `components/3d/FieldVisualizer.tsx`, `components/3d/PlayerCharacter.tsx`).")
doc.append("2. Clean up redundant barrel files (`components/news/index.ts`, `components/trades/index.ts`, `components/transitions/index.ts`).")
doc.append("3. Deduplicate `TraitBadge` between `components/common/`, `components/shared/`, and `components/skills/`.")
doc.append("")

with open(OUT_FILE, "w", encoding="utf-8") as out:
    out.write("\n".join(doc))

print(f"Generated comprehensive survey at {OUT_FILE} ({len(doc)} lines).")
