"""Add proposed feature enhancements and models

Revision ID: 00d0f05763a5
Revises: 6b7dacdbe3be
Create Date: 2025-12-04 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d0f05763a5'
down_revision: Union[str, Sequence[str], None] = '6b7dacdbe3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('surface_type', sa.String(), nullable=True),
    sa.Column('is_dome', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stadium', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stadium_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stadium_name'), ['name'], unique=False)

    op.create_table('fan_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('loyalty_rating', sa.Float(), nullable=True),
    sa.Column('market_size', sa.Float(), nullable=True),
    sa.Column('current_happiness', sa.Float(), nullable=True),
    sa.Column('engagement_multiplier', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fan_base', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fan_base_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fan_base_team_id'), ['team_id'], unique=False)

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stadium_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_team_stadium_id', 'stadium', ['stadium_id'], ['id'])

    with op.batch_alter_table('stadium_climate', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_stadium_climate_stadium_id', 'stadium', ['stadium_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stadium_climate', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stadium_climate_stadium_id', type_='foreignkey')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_stadium_id', type_='foreignkey')
        batch_op.drop_column('stadium_id')

    with op.batch_alter_table('fan_base', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fan_base_team_id'))
        batch_op.drop_index(batch_op.f('ix_fan_base_id'))

    op.drop_table('fan_base')
    with op.batch_alter_table('stadium', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stadium_name'))
        batch_op.drop_index(batch_op.f('ix_stadium_id'))

    op.drop_table('stadium')
    # ### end Alembic commands ###
