"""Add proposed feature enhancements and traits system

Revision ID: 00d0f05763a5
Revises: 6e7b75fed3d6
Create Date: 2025-12-02 14:24:30.873809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '00d0f05763a5'
down_revision: Union[str, Sequence[str], None] = '6e7b75fed3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player_traits',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('trait_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['trait_id'], ['traits.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'trait_id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pocket_presence', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('quick_release', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('scramble_willingness', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('throw_on_run', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('patience', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('pass_pro_rating', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('juke_efficiency', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('release', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('blocking_tenacity', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('pull_speed', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('anchor', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('discipline', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('first_step', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('gap_integrity', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('coverage_disguise', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('blitz_timing', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('run_fit', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('press', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ball_tracking', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('run_support', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('hang_time', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('coffin_corner', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('return_vision', sa.Integer(), nullable=False, server_default='0'))
        batch_op.drop_column('traits')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('traits', sqlite.JSON(), nullable=True))
        batch_op.drop_column('return_vision')
        batch_op.drop_column('coffin_corner')
        batch_op.drop_column('hang_time')
        batch_op.drop_column('run_support')
        batch_op.drop_column('ball_tracking')
        batch_op.drop_column('press')
        batch_op.drop_column('run_fit')
        batch_op.drop_column('blitz_timing')
        batch_op.drop_column('coverage_disguise')
        batch_op.drop_column('gap_integrity')
        batch_op.drop_column('first_step')
        batch_op.drop_column('discipline')
        batch_op.drop_column('anchor')
        batch_op.drop_column('pull_speed')
        batch_op.drop_column('blocking_tenacity')
        batch_op.drop_column('release')
        batch_op.drop_column('juke_efficiency')
        batch_op.drop_column('pass_pro_rating')
        batch_op.drop_column('patience')
        batch_op.drop_column('throw_on_run')
        batch_op.drop_column('scramble_willingness')
        batch_op.drop_column('quick_release')
        batch_op.drop_column('pocket_presence')

    op.drop_table('player_traits')
    op.drop_table('traits')
    # ### end Alembic commands ###
