"""decompose_player_model

Revision ID: 126ecc4d4b88
Revises: 606b80b15382
Create Date: 2025-12-17 18:21:22.067794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '126ecc4d4b88'
down_revision: Union[str, Sequence[str], None] = '606b80b15382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('acceleration', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('awareness', sa.Integer(), nullable=False),


    sa.Column('throw_power', sa.Integer(), nullable=False),
    sa.Column('throw_accuracy_short', sa.Integer(), nullable=False),
    sa.Column('throw_accuracy_mid', sa.Integer(), nullable=False),
    sa.Column('throw_accuracy_deep', sa.Integer(), nullable=False),
    sa.Column('catching', sa.Integer(), nullable=False),
    sa.Column('route_running', sa.Integer(), nullable=False),
    sa.Column('pass_block', sa.Integer(), nullable=False),
    sa.Column('run_block', sa.Integer(), nullable=False),
    sa.Column('tackle', sa.Integer(), nullable=False),
    sa.Column('hit_power', sa.Integer(), nullable=False),
    sa.Column('block_shed', sa.Integer(), nullable=False),
    sa.Column('man_coverage', sa.Integer(), nullable=False),
    sa.Column('zone_coverage', sa.Integer(), nullable=False),
    sa.Column('pass_rush_power', sa.Integer(), nullable=False),
    sa.Column('pass_rush_finesse', sa.Integer(), nullable=False),

    sa.Column('kick_power', sa.Integer(), nullable=False),
    sa.Column('kick_accuracy', sa.Integer(), nullable=False),
    sa.Column('pocket_presence', sa.Integer(), nullable=False),
    sa.Column('quick_release', sa.Integer(), nullable=False),
    sa.Column('scramble_willingness', sa.Integer(), nullable=False),
    sa.Column('throw_on_run', sa.Integer(), nullable=False),
    sa.Column('patience', sa.Integer(), nullable=False),
    sa.Column('pass_pro_rating', sa.Integer(), nullable=False),
    sa.Column('juke_efficiency', sa.Integer(), nullable=False),
    sa.Column('release', sa.Integer(), nullable=False),
    sa.Column('blocking_tenacity', sa.Integer(), nullable=False),
    sa.Column('pull_speed', sa.Integer(), nullable=False),
    sa.Column('anchor', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.Integer(), nullable=False),
    sa.Column('first_step', sa.Integer(), nullable=False),
    sa.Column('gap_integrity', sa.Integer(), nullable=False),
    sa.Column('coverage_disguise', sa.Integer(), nullable=False),
    sa.Column('blitz_timing', sa.Integer(), nullable=False),
    sa.Column('run_fit', sa.Integer(), nullable=False),
    sa.Column('press', sa.Integer(), nullable=False),
    sa.Column('ball_tracking', sa.Integer(), nullable=False),
    sa.Column('run_support', sa.Integer(), nullable=False),
    sa.Column('hang_time', sa.Integer(), nullable=False),
    sa.Column('coffin_corner', sa.Integer(), nullable=False),
    sa.Column('return_vision', sa.Integer(), nullable=False),
    sa.Column('forty_yard_dash', sa.Float(), nullable=True),
    sa.Column('bench_press', sa.Integer(), nullable=True),
    sa.Column('vertical_jump', sa.Float(), nullable=True),
    sa.Column('broad_jump', sa.Integer(), nullable=True),
    sa.Column('three_cone_drill', sa.Float(), nullable=True),
    sa.Column('twenty_yard_shuttle', sa.Float(), nullable=True),
    sa.Column('power_clean_max', sa.Integer(), nullable=True),
    sa.Column('gps_speed_max', sa.Float(), nullable=True),
    sa.Column('s2_cognition_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_attributes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_attributes_player_id'), ['player_id'], unique=True)

    op.create_table('player_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('contract_years', sa.Integer(), nullable=False),
    sa.Column('contract_salary', sa.Integer(), nullable=False),
    sa.Column('is_rookie', sa.Boolean(), nullable=False),




    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_contract', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_contract_player_id'), ['player_id'], unique=True)

    op.create_table('player_injury',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),







    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_injury', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_injury_player_id'), ['player_id'], unique=True)

    op.create_table('player_physics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('arm_slot', sa.String(), nullable=False),
    sa.Column('release_point_height', sa.Float(), nullable=False),
    sa.Column('vision_cone_angle', sa.Integer(), nullable=False),
    sa.Column('break_tackle_threshold', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_physics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_physics_player_id'), ['player_id'], unique=True)

    op.create_table('player_progression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('skill_points', sa.Integer(), nullable=False),

    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('attribute_xp', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_progression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_progression_player_id'), ['player_id'], unique=True)

    # --- Data Migration: Preserving Data ---
    # 1. Player Attributes
    op.execute("""
        INSERT INTO player_attributes (
            player_id,
            speed, acceleration, strength, agility, awareness,
            throw_power, throw_accuracy_short, throw_accuracy_mid, throw_accuracy_deep,
            catching, route_running, pass_block, run_block,
            tackle, hit_power, block_shed, man_coverage, zone_coverage,
            pass_rush_power, pass_rush_finesse,
            kick_power, kick_accuracy,
            pocket_presence, quick_release, scramble_willingness, throw_on_run,
            patience, pass_pro_rating, juke_efficiency,
            release, blocking_tenacity,
            pull_speed, anchor, discipline,
            first_step, gap_integrity,
            coverage_disguise, blitz_timing, run_fit,
            press, ball_tracking, run_support,
            hang_time, coffin_corner, return_vision,
            forty_yard_dash, bench_press, vertical_jump, broad_jump, three_cone_drill, twenty_yard_shuttle,
            power_clean_max, gps_speed_max, s2_cognition_score
        )
        SELECT
            id,
            speed, acceleration, strength, agility, awareness,
            throw_power, throw_accuracy_short, throw_accuracy_mid, throw_accuracy_deep,
            catching, route_running, pass_block, run_block,
            tackle, hit_power, block_shed, man_coverage, zone_coverage,
            pass_rush_power, pass_rush_finesse,
            kick_power, kick_accuracy,
            pocket_presence, quick_release, scramble_willingness, throw_on_run,
            patience, pass_pro_rating, juke_efficiency,
            release, blocking_tenacity,
            pull_speed, anchor, discipline,
            first_step, gap_integrity,
            coverage_disguise, blitz_timing, run_fit,
            press, ball_tracking, run_support,
            hang_time, coffin_corner, return_vision,
            forty_yard_dash, bench_press, vertical_jump, broad_jump, three_cone_drill, twenty_yard_shuttle,
            power_clean_max, gps_speed_max, s2_cognition_score
        FROM player
    """)

    # 2. Player Contract
    op.execute("""
        INSERT INTO player_contract (
            player_id, contract_years, contract_salary, is_rookie
        )
        SELECT
            id, contract_years, contract_salary, is_rookie
        FROM player
    """)

    # 3. Player Injury
    pass

    # 4. Player Physics
    op.execute("""
        INSERT INTO player_physics (
            player_id, arm_slot, release_point_height, vision_cone_angle, break_tackle_threshold
        )
        SELECT
            id, arm_slot, release_point_height, vision_cone_angle, break_tackle_threshold
        FROM player
    """)

    # 5. Player Progression (Note: attribute_xp is new, so not selected)
    op.execute("""
        INSERT INTO player_progression (
            player_id, xp, level, skill_points, abilities
        )
        SELECT
            id, xp, level, skill_points, abilities
        FROM player
    """)

    pass # op.drop_table('_alembic_tmp_traits')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribute_xp', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('attribute_xp')

    if False:
        op.create_table('_alembic_tmp_traits',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('effect_type', sa.VARCHAR(length=11), nullable=False),
    sa.Column('effect_value', sa.FLOAT(), nullable=False),
    sa.Column('position_groups', sqlite.JSON(), nullable=True),
    sa.Column('tier', sa.VARCHAR(length=6), nullable=False),
    sa.Column('is_badge', sa.BOOLEAN(), nullable=False),
    sa.Column('icon_url', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('player_progression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_progression_player_id'))

    op.drop_table('player_progression')
    with op.batch_alter_table('player_physics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_physics_player_id'))

    op.drop_table('player_physics')
    with op.batch_alter_table('player_injury', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_injury_player_id'))

    op.drop_table('player_injury')
    with op.batch_alter_table('player_contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_contract_player_id'))

    op.drop_table('player_contract')
    with op.batch_alter_table('player_attributes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_attributes_player_id'))

    op.drop_table('player_attributes')
    # ### end Alembic commands ###
