"""add_injury_severity_fields

Revision ID: 38aaa7c32477
Revises: 6b7dacdbe3be
Create Date: 2025-12-03 21:50:49.176329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38aaa7c32477'
down_revision: Union[str, Sequence[str], None] = '6b7dacdbe3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('injury_severity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('injury_recurrence_risk', sa.Float(), nullable=True))

    with op.batch_alter_table('player_game_starts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_pgs_game_position'))
        batch_op.drop_index(batch_op.f('idx_pgs_ol_only'))
        batch_op.drop_index(batch_op.f('idx_pgs_team_game'))
        batch_op.drop_index(batch_op.f('idx_pgs_team_position'))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medical_rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('training_staff_quality', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medical_budget', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('medical_budget')
        batch_op.drop_column('training_staff_quality')
        batch_op.drop_column('medical_rating')

    with op.batch_alter_table('player_game_starts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_pgs_team_position'), ['team_id', 'position', 'week'], unique=False)
        batch_op.create_index(batch_op.f('idx_pgs_team_game'), ['team_id', 'game_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_pgs_ol_only'), ['team_id', 'game_id', 'position'], unique=False)
        batch_op.create_index(batch_op.f('idx_pgs_game_position'), ['game_id', 'position'], unique=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('injury_recurrence_risk')
        batch_op.drop_column('injury_severity')

    # ### end Alembic commands ###
