"""ensure_indexes

Revision ID: 3dc5f2df700e
Revises: 519b2f576b43
Create Date: 2025-11-29 23:32:48.647500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc5f2df700e'
down_revision: Union[str, Sequence[str], None] = '519b2f576b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_draft_pick_pick_number'), 'draft_pick', ['pick_number'], unique=False)
    op.create_index(op.f('ix_draft_pick_round'), 'draft_pick', ['round'], unique=False)
    op.create_index(op.f('ix_draft_pick_season_id'), 'draft_pick', ['season_id'], unique=False)
    op.create_index('ix_draft_pick_season_round', 'draft_pick', ['season_id', 'round'], unique=False)
    op.create_index(op.f('ix_draft_pick_team_id'), 'draft_pick', ['team_id'], unique=False)
    op.create_index('ix_game_season_week', 'game', ['season_id', 'week'], unique=False)
    op.create_index(op.f('ix_player_is_rookie'), 'player', ['is_rookie'], unique=False)
    op.create_index(op.f('ix_player_overall_rating'), 'player', ['overall_rating'], unique=False)
    op.create_index(op.f('ix_player_position'), 'player', ['position'], unique=False)
    op.create_index(op.f('ix_player_team_id'), 'player', ['team_id'], unique=False)
    op.create_index(op.f('ix_playergamestats_game_id'), 'playergamestats', ['game_id'], unique=False)
    op.create_index(op.f('ix_playergamestats_player_id'), 'playergamestats', ['player_id'], unique=False)
    op.create_index(op.f('ix_playergamestats_team_id'), 'playergamestats', ['team_id'], unique=False)
    op.create_index(op.f('ix_playoff_matchup_season_id'), 'playoff_matchup', ['season_id'], unique=False)
    op.create_index('ix_playoff_matchup_season_round', 'playoff_matchup', ['season_id', 'round'], unique=False)
    op.create_index(op.f('ix_team_conference'), 'team', ['conference'], unique=False)
    op.create_index(op.f('ix_team_division'), 'team', ['division'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_division'), table_name='team')
    op.drop_index(op.f('ix_team_conference'), table_name='team')
    op.drop_index('ix_playoff_matchup_season_round', table_name='playoff_matchup')
    op.drop_index(op.f('ix_playoff_matchup_season_id'), table_name='playoff_matchup')
    op.drop_index(op.f('ix_playergamestats_team_id'), table_name='playergamestats')
    op.drop_index(op.f('ix_playergamestats_player_id'), table_name='playergamestats')
    op.drop_index(op.f('ix_playergamestats_game_id'), table_name='playergamestats')
    op.drop_index(op.f('ix_player_team_id'), table_name='player')
    op.drop_index(op.f('ix_player_position'), table_name='player')
    op.drop_index(op.f('ix_player_overall_rating'), table_name='player')
    op.drop_index(op.f('ix_player_is_rookie'), table_name='player')
    op.drop_index('ix_game_season_week', table_name='game')
    op.drop_index(op.f('ix_draft_pick_team_id'), table_name='draft_pick')
    op.drop_index('ix_draft_pick_season_round', table_name='draft_pick')
    op.drop_index(op.f('ix_draft_pick_season_id'), table_name='draft_pick')
    op.drop_index(op.f('ix_draft_pick_round'), table_name='draft_pick')
    op.drop_index(op.f('ix_draft_pick_pick_number'), table_name='draft_pick')
    # ### end Alembic commands ###
