"""Add tier is_badge icon_url to traits

Revision ID: 482207e93bab
Revises: 2967256eac80
Create Date: 2025-12-16 21:36:06.428210

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '482207e93bab'
down_revision: str | Sequence[str] | None = '2967256eac80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.Enum('GOLD', 'SILVER', 'BRONZE', 'COMMON', name='traittier'), nullable=True))
        batch_op.add_column(sa.Column('is_badge', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('icon_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traits', schema=None) as batch_op:
        batch_op.drop_column('icon_url')
        batch_op.drop_column('is_badge')
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
