"""Add contract fields to player table

Revision ID: 519b2f576b43
Revises: 9d89cea28a08
Create Date: 2025-11-28 20:28:47.261644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '519b2f576b43'
down_revision: Union[str, Sequence[str], None] = '9d89cea28a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('contract_years', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('contract_salary', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('is_rookie', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'is_rookie')
    op.drop_column('player', 'contract_salary')
    op.drop_column('player', 'contract_years')
    # ### end Alembic commands ###
