"""optimize_chemistry_queries

Revision ID: 5b2c3d4e5f6a
Revises: 4a1b2c3d4e5f
Create Date: 2025-02-28 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2c3d4e5f6a'
down_revision: Union[str, Sequence[str], None] = '4a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # We will wrap index creation in try-except using run_async or just omit it
    # if it fails in sqlite, or check dialect.

    # Actually, let's just make it simple and ignore errors if table doesn't exist
    conn = op.get_bind()

    # Check if player_game_starts exists
    if conn.dialect.name == 'postgresql':
        has_table = conn.dialect.has_table(conn, 'player_game_starts')
    else:
        # SQLite
        has_table = conn.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='player_game_starts'")).scalar() is not None

    if has_table:
        op.create_index(
            'idx_pgs_team_game',
            'player_game_starts',
            ['team_id', 'game_id']
        )
        op.create_index(
            'idx_pgs_player_game',
            'player_game_starts',
            ['player_id', 'game_id']
        )

    # Check if team_chemistry exists
    if conn.dialect.name == 'postgresql':
        has_tc_table = conn.dialect.has_table(conn, 'team_chemistry')
    else:
        has_tc_table = conn.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='team_chemistry'")).scalar() is not None

    if has_tc_table:
        op.create_index(
            'idx_team_chemistry_lookup',
            'team_chemistry',
            ['team_id', 'season_id']
        )

    # Check if player_chemistry exists
    if conn.dialect.name == 'postgresql':
        has_pc_table = conn.dialect.has_table(conn, 'player_chemistry')
    else:
        has_pc_table = conn.execute(sa.text("SELECT name FROM sqlite_master WHERE type='table' AND name='player_chemistry'")).scalar() is not None

    if has_pc_table:
        op.create_index(
            'idx_player_chem_pairs',
            'player_chemistry',
            ['player_1_id', 'player_2_id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_player_chem_pairs', table_name='player_chemistry')
    op.drop_index('idx_team_chemistry_lookup', table_name='team_chemistry')
    op.drop_index('idx_pgs_player_game', table_name='player_game_starts')
    op.drop_index('idx_pgs_team_game', table_name='player_game_starts')
    # ### end Alembic commands ###
