"""Add NewsItem, WeeklyRecap, RPGEvent

Revision ID: 606b80b15382
Revises: 482207e93bab
Create Date: 2025-12-16 23:15:47.036711

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '606b80b15382'
down_revision: str | Sequence[str] | None = '482207e93bab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('TRANSACTION', 'INJURY', 'GAME_RESULT', 'RUMOR', 'QUOTE', 'LEAGUE_NEWS', 'DRAFT_NEWS', 'CONTROVERSY', 'NARRATIVE', name='newscategory'), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpg_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weekly_recaps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('mvp_player_id', sa.Integer(), nullable=True),
    sa.Column('play_of_the_week_id', sa.String(), nullable=True),
    sa.Column('surprising_result', sa.Text(), nullable=True),
    sa.Column('media_assets', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mvp_player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Trait alterations removed to prevent SQLite constraint failures on upgrade
    # with op.batch_alter_table('traits', schema=None) as batch_op:
    #     batch_op.alter_column('tier', existing_type=sa.VARCHAR(length=6), nullable=False)
    #     batch_op.alter_column('is_badge', existing_type=sa.BOOLEAN(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traits', schema=None) as batch_op:
        batch_op.alter_column('is_badge',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    op.drop_table('weekly_recaps')
    op.drop_table('rpg_events')
    op.drop_table('news_items')
    # ### end Alembic commands ###
