"""Add weather models

Revision ID: 6b7dacdbe3be
Revises: 5ed9ccf039c1
Create Date: 2025-12-03 20:41:06.842282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7dacdbe3be'
down_revision: Union[str, Sequence[str], None] = '5ed9ccf039c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadium_climate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('avg_temp_by_month', sa.JSON(), nullable=True),
    sa.Column('precip_chance_by_month', sa.JSON(), nullable=True),
    sa.Column('wind_avg_by_month', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadium.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stadium_id')
    )
    with op.batch_alter_table('stadium_climate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stadium_climate_id'), ['id'], unique=False)

    op.create_table('game_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(), nullable=True),
    sa.Column('precipitation_type', sa.String(), nullable=True),
    sa.Column('precipitation_intensity', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('field_condition', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    with op.batch_alter_table('game_weather', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_weather_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('game_weather', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_weather_id'))

    op.drop_table('game_weather')
    with op.batch_alter_table('stadium_climate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stadium_climate_id'))

    op.drop_table('stadium_climate')
    # ### end Alembic commands ###
