"""add_season_id_to_playergamestats

Revision ID: 6e7b75fed3d6
Revises: 4a1b2c3d4e5f
Create Date: 2025-12-01 20:23:33.977443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7b75fed3d6'
down_revision: Union[str, Sequence[str], None] = '4a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playergamestats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_playergamestats_season_id'), ['season_id'], unique=False)
        batch_op.create_foreign_key('fk_playergamestats_season_id', 'season', ['season_id'], ['id'])

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_team_stadium_id', 'stadium', ['stadium_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_constraint('fk_team_stadium_id', type_='foreignkey')

    with op.batch_alter_table('playergamestats', schema=None) as batch_op:
        batch_op.drop_constraint('fk_playergamestats_season_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_playergamestats_season_id'))
        batch_op.drop_column('season_id')

    # ### end Alembic commands ###
