"""Add TradeOffer model

Revision ID: 870837d208c2
Revises: 9a82acf7dee9
Create Date: 2025-12-10 08:06:23.150247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870837d208c2'
down_revision: Union[str, Sequence[str], None] = '9a82acf7dee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_team_id', sa.Integer(), nullable=False),
    sa.Column('receiving_team_id', sa.Integer(), nullable=False),
    sa.Column('offered_player_ids', sa.JSON(), nullable=True),
    sa.Column('requested_player_ids', sa.JSON(), nullable=True),
    sa.Column('offered_picks', sa.JSON(), nullable=True),
    sa.Column('requested_picks', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'COUNTERED', 'EXPIRED', 'WITHDRAWN', name='tradeofferstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('gm_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('parent_offer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offering_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['parent_offer_id'], ['trade_offer.id'], ),
    sa.ForeignKeyConstraint(['receiving_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_offer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_offer_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_offer_offering_team_id'), ['offering_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_offer_receiving_team_id'), ['receiving_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_offer_status'), ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_offer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_offer_status'))
        batch_op.drop_index(batch_op.f('ix_trade_offer_receiving_team_id'))
        batch_op.drop_index(batch_op.f('ix_trade_offer_offering_team_id'))
        batch_op.drop_index(batch_op.f('ix_trade_offer_id'))

    op.drop_table('trade_offer')
    # ### end Alembic commands ###

