"""Add medical staff fields to Team

Revision ID: 9595badce323
Revises: 38aaa7c32477
Create Date: 2025-12-03 21:56:12.960431

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '9595badce323'
down_revision: str | Sequence[str] | None = '38aaa7c32477'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
