"""add_combine_genesis_fields

Revision ID: 9a82acf7dee9
Revises: 9595badce323
Create Date: 2025-12-08 21:57:15.313602

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a82acf7dee9'
down_revision: str | Sequence[str] | None = '9595badce323'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forty_yard_dash', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bench_press', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vertical_jump', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('broad_jump', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('three_cone_drill', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('twenty_yard_shuttle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('power_clean_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gps_speed_max', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('s2_cognition_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medical_flags', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('genesis_revealed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('genesis_revealed')
        batch_op.drop_column('medical_flags')
        batch_op.drop_column('s2_cognition_score')
        batch_op.drop_column('gps_speed_max')
        batch_op.drop_column('power_clean_max')
        batch_op.drop_column('twenty_yard_shuttle')
        batch_op.drop_column('three_cone_drill')
        batch_op.drop_column('broad_jump')
        batch_op.drop_column('vertical_jump')
        batch_op.drop_column('bench_press')
        batch_op.drop_column('forty_yard_dash')

    # ### end Alembic commands ###
