"""Add playoff tables

Revision ID: 9d89cea28a08
Revises: db3fab50bb95
Create Date: 2025-11-28 01:20:26.450566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d89cea28a08'
down_revision: Union[str, Sequence[str], None] = 'db3fab50bb95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('original_team_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('pick_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['original_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_draft_pick_id'), 'draft_pick', ['id'], unique=False)
    op.create_table('playoff_matchup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Enum('WILD_CARD', 'DIVISIONAL', 'CONFERENCE', 'SUPER_BOWL', name='playoffround'), nullable=False),
    sa.Column('conference', sa.Enum('AFC', 'NFC', 'SUPER_BOWL', name='playoffconference'), nullable=False),
    sa.Column('matchup_code', sa.String(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_team_seed', sa.Integer(), nullable=True),
    sa.Column('away_team_seed', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playoff_matchup_id'), 'playoff_matchup', ['id'], unique=False)
    op.create_foreign_key(None, 'game', 'season', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_index(op.f('ix_playoff_matchup_id'), table_name='playoff_matchup')
    op.drop_table('playoff_matchup')
    op.drop_index(op.f('ix_draft_pick_id'), table_name='draft_pick')
    op.drop_table('draft_pick')
    # ### end Alembic commands ###
