"""Add PlayerGameStart table

Revision ID: aa400ba86838
Revises: 00d0f05763a5
Create Date: 2025-12-02 14:28:41.587019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa400ba86838'
down_revision: Union[str, Sequence[str], None] = '00d0f05763a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_game_starts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_game_starts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_starts_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_starts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_starts_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_starts_season_id'), ['season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_starts_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game_starts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_starts_team_id'))
        batch_op.drop_index(batch_op.f('ix_player_game_starts_season_id'))
        batch_op.drop_index(batch_op.f('ix_player_game_starts_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_game_starts_id'))
        batch_op.drop_index(batch_op.f('ix_player_game_starts_game_id'))

    op.drop_table('player_game_starts')
    # ### end Alembic commands ###
