"""Add player details

Revision ID: d28b1ad1af95
Revises: dd6f48825b16
Create Date: 2025-11-24 12:45:34.597860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28b1ad1af95'
down_revision: Union[str, Sequence[str], None] = 'dd6f48825b16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('experience', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('jersey_number', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('overall_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'overall_rating')
    op.drop_column('player', 'jersey_number')
    op.drop_column('player', 'experience')
    # ### end Alembic commands ###
