"""Add GMDecision model

Revision ID: d68652484c61
Revises: aa400ba86838
Create Date: 2025-12-02 21:39:16.896092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68652484c61'
down_revision: Union[str, Sequence[str], None] = 'aa400ba86838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gm_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gm_id', sa.Integer(), nullable=True),
    sa.Column('decision_type', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['gm_id'], ['gm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gm_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gm_decisions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gm_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gm_decisions_id'))

    op.drop_table('gm_decisions')
    # ### end Alembic commands ###
