"""drop_redundant_player_columns

Revision ID: da6e871020ca
Revises: 126ecc4d4b88
Create Date: 2025-12-17 19:32:10.406225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'da6e871020ca'
down_revision: Union[str, Sequence[str], None] = '126ecc4d4b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocking_tenacity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('speed', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('pass_rush_finesse', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('morale', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('abilities', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('weeks_to_recovery', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('run_support', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('discipline', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('retirement_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('return_vision', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('injury_severity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('throw_on_run', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('juke_efficiency', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('vision_cone_angle', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('coffin_corner', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('contract_years', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('zone_coverage', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('twenty_yard_shuttle', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('acceleration', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('block_shed', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('press', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('medical_flags', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('legacy_score', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('hit_power', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('bench_press', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('coverage_disguise', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('gps_speed_max', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('skill_points', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('throw_accuracy_short', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('release', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('blitz_timing', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('throw_accuracy_mid', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('patience', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('run_block', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('pass_block', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('attribute_xp', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('run_fit', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('pull_speed', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('kick_accuracy', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('is_rookie', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('awareness', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('injury_recurrence_risk', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('agility', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('hang_time', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('forty_yard_dash', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pass_pro_rating', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('release_point_height', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('quick_release', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('genesis_revealed', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('tackle', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('strength', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('injury_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('scramble_willingness', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('injury_resistance', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('is_retired', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('gap_integrity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('stamina', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('contract_salary', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('s2_cognition_score', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('broad_jump', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pass_rush_power', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('power_clean_max', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('man_coverage', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('throw_accuracy_deep', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('throw_power', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('play_recognition', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('catching', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('route_running', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('three_cone_drill', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('vertical_jump', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pocket_presence', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('kick_power', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('xp', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('first_step', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('injury_status', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('break_tackle_threshold', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('anchor', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('development_trait', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('ball_tracking', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('arm_slot', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_player_is_rookie'), ['is_rookie'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_is_retired'), ['is_retired'], unique=False)

    # ### end Alembic commands ###
