"""drop_redundant_player_columns

Revision ID: da6e871020ca
Revises: 126ecc4d4b88
Create Date: 2025-12-17 19:32:10.406225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'da6e871020ca'
down_revision: Union[str, Sequence[str], None] = '126ecc4d4b88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    inspector = inspect(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        pass # batch_op.drop_index(batch_op.f('ix_player_is_retired'))
        batch_op.drop_index(batch_op.f('ix_player_is_rookie'))
        if 'arm_slot' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('arm_slot')
        if 'ball_tracking' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('ball_tracking')
        if 'development_trait' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('development_trait')
        if 'anchor' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('anchor')
        if 'break_tackle_threshold' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('break_tackle_threshold')
        if 'injury_status' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('injury_status')
        if 'first_step' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('first_step')
        if 'xp' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('xp')
        if 'kick_power' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('kick_power')
        if 'pocket_presence' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('pocket_presence')
        if 'vertical_jump' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('vertical_jump')
        if 'three_cone_drill' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('three_cone_drill')
        if 'route_running' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('route_running')
        if 'catching' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('catching')
        if 'play_recognition' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('play_recognition')
        if 'throw_power' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('throw_power')
        if 'throw_accuracy_deep' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('throw_accuracy_deep')
        if 'man_coverage' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('man_coverage')
        if 'power_clean_max' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('power_clean_max')
        if 'pass_rush_power' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('pass_rush_power')
        if 'broad_jump' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('broad_jump')
        if 's2_cognition_score' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('s2_cognition_score')
        if 'contract_salary' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('contract_salary')
        if 'stamina' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('stamina')
        if 'gap_integrity' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('gap_integrity')
        if 'is_retired' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('is_retired')
        if 'injury_resistance' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('injury_resistance')
        if 'scramble_willingness' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('scramble_willingness')
        if 'injury_type' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('injury_type')
        if 'strength' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('strength')
        if 'tackle' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('tackle')
        if 'genesis_revealed' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('genesis_revealed')
        if 'quick_release' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('quick_release')
        if 'release_point_height' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('release_point_height')
        if 'pass_pro_rating' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('pass_pro_rating')
        if 'forty_yard_dash' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('forty_yard_dash')
        if 'hang_time' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('hang_time')
        if 'agility' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('agility')
        if 'injury_recurrence_risk' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('injury_recurrence_risk')
        if 'awareness' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('awareness')
        if 'is_rookie' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('is_rookie')
        if 'kick_accuracy' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('kick_accuracy')
        if 'pull_speed' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('pull_speed')
        if 'run_fit' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('run_fit')
        if 'attribute_xp' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('attribute_xp')
        if 'pass_block' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('pass_block')
        if 'run_block' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('run_block')
        if 'patience' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('patience')
        if 'throw_accuracy_mid' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('throw_accuracy_mid')
        if 'blitz_timing' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('blitz_timing')
        if 'release' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('release')
        if 'throw_accuracy_short' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('throw_accuracy_short')
        if 'skill_points' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('skill_points')
        if 'gps_speed_max' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('gps_speed_max')
        if 'coverage_disguise' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('coverage_disguise')
        if 'bench_press' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('bench_press')
        if 'hit_power' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('hit_power')
        if 'legacy_score' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('legacy_score')
        if 'medical_flags' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('medical_flags')
        if 'press' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('press')
        if 'block_shed' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('block_shed')
        if 'acceleration' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('acceleration')
        if 'twenty_yard_shuttle' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('twenty_yard_shuttle')
        if 'zone_coverage' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('zone_coverage')
        if 'contract_years' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('contract_years')
        if 'coffin_corner' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('coffin_corner')
        if 'vision_cone_angle' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('vision_cone_angle')
        if 'juke_efficiency' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('juke_efficiency')
        if 'throw_on_run' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('throw_on_run')
        if 'injury_severity' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('injury_severity')
        if 'return_vision' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('return_vision')
        if 'level' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('level')
        if 'retirement_year' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('retirement_year')
        if 'discipline' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('discipline')
        if 'run_support' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('run_support')
        if 'weeks_to_recovery' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('weeks_to_recovery')
        if 'abilities' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('abilities')
        if 'morale' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('morale')
        if 'pass_rush_finesse' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('pass_rush_finesse')
        if 'speed' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('speed')
        if 'blocking_tenacity' in [c['name'] for c in inspector.get_columns('player')]:
            batch_op.drop_column('blocking_tenacity')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocking_tenacity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('speed', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('pass_rush_finesse', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('morale', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('abilities', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('weeks_to_recovery', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('run_support', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('discipline', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('retirement_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('return_vision', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('injury_severity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('throw_on_run', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('juke_efficiency', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('vision_cone_angle', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('coffin_corner', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('contract_years', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('zone_coverage', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('twenty_yard_shuttle', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('acceleration', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('block_shed', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('press', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('medical_flags', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('legacy_score', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('hit_power', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('bench_press', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('coverage_disguise', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('gps_speed_max', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('skill_points', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('throw_accuracy_short', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('release', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('blitz_timing', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('throw_accuracy_mid', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('patience', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('run_block', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('pass_block', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('attribute_xp', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('run_fit', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('pull_speed', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('kick_accuracy', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('is_rookie', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('awareness', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('injury_recurrence_risk', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('agility', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('hang_time', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('forty_yard_dash', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pass_pro_rating', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('release_point_height', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('quick_release', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('genesis_revealed', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('tackle', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('strength', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('injury_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('scramble_willingness', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('injury_resistance', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('is_retired', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('gap_integrity', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('stamina', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('contract_salary', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('s2_cognition_score', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('broad_jump', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('pass_rush_power', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('power_clean_max', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('man_coverage', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('throw_accuracy_deep', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('throw_power', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('play_recognition', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('catching', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('route_running', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('three_cone_drill', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('vertical_jump', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('pocket_presence', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('kick_power', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('xp', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('first_step', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('injury_status', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('break_tackle_threshold', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('anchor', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('development_trait', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('ball_tracking', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('arm_slot', sa.VARCHAR(), nullable=False))
        batch_op.create_index(batch_op.f('ix_player_is_rookie'), ['is_rookie'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_is_retired'), ['is_retired'], unique=False)

    # ### end Alembic commands ###
