"""Add Season model and update Game with season_id

Revision ID: db3fab50bb95
Revises: d28b1ad1af95
Create Date: 2025-11-25 11:20:18.791271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3fab50bb95'
down_revision: Union[str, Sequence[str], None] = 'd28b1ad1af95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('PRE_SEASON', 'REGULAR_SEASON', 'POST_SEASON', 'OFF_SEASON', name='seasonstatus'), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=True),
    sa.Column('playoff_weeks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_id'), 'season', ['id'], unique=False)
    op.create_index(op.f('ix_season_is_active'), 'season', ['is_active'], unique=False)
    op.create_index(op.f('ix_season_year'), 'season', ['year'], unique=True)
    
    # Use batch mode for SQLite compatibility
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_season_id'), ['season_id'], unique=False)
        batch_op.create_foreign_key('fk_game_season_id', 'season', ['season_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_season_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_game_season_id'))
        batch_op.drop_column('season_id')
    
    op.drop_index(op.f('ix_season_year'), table_name='season')
    op.drop_index(op.f('ix_season_is_active'), table_name='season')
    op.drop_index(op.f('ix_season_id'), table_name='season')
    op.drop_table('season')
    # ### end Alembic commands ###
