"""Initial schema

Revision ID: dd6f48825b16
Revises: 
Create Date: 2025-11-24 09:00:18.930208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6f48825b16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('conference', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('prestige', sa.Integer(), nullable=True),
    sa.Column('salary_cap_space', sa.Float(), nullable=True),
    sa.Column('fan_support', sa.Integer(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('primary_color', sa.String(), nullable=True),
    sa.Column('secondary_color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_abbreviation'), 'team', ['abbreviation'], unique=True)
    op.create_index(op.f('ix_team_city'), 'team', ['city'], unique=False)
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    op.create_table('coach',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('offense_rating', sa.Integer(), nullable=True),
    sa.Column('defense_rating', sa.Integer(), nullable=True),
    sa.Column('development_rating', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_id'), 'coach', ['id'], unique=False)
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_playoff', sa.Boolean(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('is_played', sa.Boolean(), nullable=True),
    sa.Column('game_data', sa.JSON(), nullable=True),
    sa.Column('weather_temperature', sa.Integer(), nullable=True),
    sa.Column('weather_condition', sa.String(), nullable=True),
    sa.Column('wind_speed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=False)
    op.create_index(op.f('ix_game_season'), 'game', ['season'], unique=False)
    op.create_index(op.f('ix_game_week'), 'game', ['week'], unique=False)
    op.create_table('gm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('scouting', sa.Integer(), nullable=True),
    sa.Column('negotiation', sa.Integer(), nullable=True),
    sa.Column('cap_management', sa.Integer(), nullable=True),
    sa.Column('owner_trust', sa.Integer(), nullable=True),
    sa.Column('league_reputation', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gm_id'), 'gm', ['id'], unique=False)
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('acceleration', sa.Integer(), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('agility', sa.Integer(), nullable=True),
    sa.Column('awareness', sa.Integer(), nullable=True),
    sa.Column('throw_power', sa.Integer(), nullable=True),
    sa.Column('throw_accuracy_short', sa.Integer(), nullable=True),
    sa.Column('throw_accuracy_mid', sa.Integer(), nullable=True),
    sa.Column('throw_accuracy_deep', sa.Integer(), nullable=True),
    sa.Column('catching', sa.Integer(), nullable=True),
    sa.Column('route_running', sa.Integer(), nullable=True),
    sa.Column('pass_block', sa.Integer(), nullable=True),
    sa.Column('run_block', sa.Integer(), nullable=True),
    sa.Column('tackle', sa.Integer(), nullable=True),
    sa.Column('hit_power', sa.Integer(), nullable=True),
    sa.Column('block_shed', sa.Integer(), nullable=True),
    sa.Column('man_coverage', sa.Integer(), nullable=True),
    sa.Column('zone_coverage', sa.Integer(), nullable=True),
    sa.Column('pass_rush_power', sa.Integer(), nullable=True),
    sa.Column('pass_rush_finesse', sa.Integer(), nullable=True),
    sa.Column('kick_power', sa.Integer(), nullable=True),
    sa.Column('kick_accuracy', sa.Integer(), nullable=True),
    sa.Column('arm_slot', sa.String(), nullable=True),
    sa.Column('release_point_height', sa.Float(), nullable=True),
    sa.Column('vision_cone_angle', sa.Integer(), nullable=True),
    sa.Column('break_tackle_threshold', sa.Float(), nullable=True),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('skill_points', sa.Integer(), nullable=True),
    sa.Column('traits', sa.JSON(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('nano_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_first_name'), 'player', ['first_name'], unique=False)
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.create_index(op.f('ix_player_last_name'), 'player', ['last_name'], unique=False)
    op.create_table('playergamestats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('pass_attempts', sa.Integer(), nullable=True),
    sa.Column('pass_completions', sa.Integer(), nullable=True),
    sa.Column('pass_yards', sa.Integer(), nullable=True),
    sa.Column('pass_tds', sa.Integer(), nullable=True),
    sa.Column('pass_ints', sa.Integer(), nullable=True),
    sa.Column('pass_sacks', sa.Integer(), nullable=True),
    sa.Column('rush_attempts', sa.Integer(), nullable=True),
    sa.Column('rush_yards', sa.Integer(), nullable=True),
    sa.Column('rush_tds', sa.Integer(), nullable=True),
    sa.Column('rush_fumbles', sa.Integer(), nullable=True),
    sa.Column('yards_after_contact', sa.Integer(), nullable=True),
    sa.Column('broken_tackles', sa.Integer(), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('rec_yards', sa.Integer(), nullable=True),
    sa.Column('rec_tds', sa.Integer(), nullable=True),
    sa.Column('drops', sa.Integer(), nullable=True),
    sa.Column('yards_after_catch', sa.Integer(), nullable=True),
    sa.Column('tackles_solo', sa.Integer(), nullable=True),
    sa.Column('tackles_assist', sa.Integer(), nullable=True),
    sa.Column('sacks', sa.Float(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('pass_deflections', sa.Integer(), nullable=True),
    sa.Column('forced_fumbles', sa.Integer(), nullable=True),
    sa.Column('tackles_for_loss', sa.Integer(), nullable=True),
    sa.Column('qb_pressures', sa.Integer(), nullable=True),
    sa.Column('fg_made', sa.Integer(), nullable=True),
    sa.Column('fg_att', sa.Integer(), nullable=True),
    sa.Column('punt_yards', sa.Integer(), nullable=True),
    sa.Column('punt_att', sa.Integer(), nullable=True),
    sa.Column('pancakes', sa.Integer(), nullable=True),
    sa.Column('sacks_allowed', sa.Integer(), nullable=True),
    sa.Column('pressures_allowed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playergamestats_id'), 'playergamestats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playergamestats_id'), table_name='playergamestats')
    op.drop_table('playergamestats')
    op.drop_index(op.f('ix_player_last_name'), table_name='player')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_index(op.f('ix_player_first_name'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_gm_id'), table_name='gm')
    op.drop_table('gm')
    op.drop_index(op.f('ix_game_week'), table_name='game')
    op.drop_index(op.f('ix_game_season'), table_name='game')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('ix_coach_id'), table_name='coach')
    op.drop_table('coach')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_index(op.f('ix_team_city'), table_name='team')
    op.drop_index(op.f('ix_team_abbreviation'), table_name='team')
    op.drop_table('team')
    # ### end Alembic commands ###
