"""Add coaching philosophy fields

Revision ID: f153bd84a19f
Revises: b2c3d4e5f6g7
Create Date: 2025-12-14 19:37:54.267392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f153bd84a19f'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LEGEND', 'ELITE', 'VETERAN', 'DEVELOPING', 'ROOKIE', name='coachtier'),
               nullable=False,
               existing_server_default=sa.text("'DEVELOPING'"))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('REGULAR', 'THANKSGIVING', 'PRIMETIME', 'PLAYOFF', 'SUPER_BOWL', name='gametype'),
               nullable=False,
               existing_server_default=sa.text("'REGULAR'"))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_type',
               existing_type=sa.Enum('REGULAR', 'THANKSGIVING', 'PRIMETIME', 'PLAYOFF', 'SUPER_BOWL', name='gametype'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'REGULAR'"))

    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.Enum('LEGEND', 'ELITE', 'VETERAN', 'DEVELOPING', 'ROOKIE', name='coachtier'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'DEVELOPING'"))

        # ### end Alembic commands ###
