"""Add coaching philosophy fields

Revision ID: f153bd84a19f
Revises: b2c3d4e5f6g7
Create Date: 2025-12-14 19:37:54.267392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f153bd84a19f'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # SQLite workaround: drop _alembic_tmp_player only if it exists
    conn = op.get_bind()
    if conn.dialect.name != 'sqlite':
        op.drop_table('_alembic_tmp_player')
    else:
        try:
            op.drop_table('_alembic_tmp_player')
        except Exception:
            pass

    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LEGEND', 'ELITE', 'VETERAN', 'DEVELOPING', 'ROOKIE', name='coachtier'),
               nullable=False,
               existing_server_default=sa.text("'DEVELOPING'"))

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('REGULAR', 'THANKSGIVING', 'PRIMETIME', 'PLAYOFF', 'SUPER_BOWL', name='gametype'),
               nullable=False,
               existing_server_default=sa.text("'REGULAR'"))

    with op.batch_alter_table('player_game_starts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_started', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('teammates_hash', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('idx_player_game', ['player_id', 'game_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_player_game_starts_teammates_hash'), ['teammates_hash'], unique=False)

    with op.batch_alter_table('player_traits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acquired_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('source', sa.Enum('DRAFT', 'DEVELOPMENT', 'MILESTONE', name='traitsource'), nullable=False))

    with op.batch_alter_table('traits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effect_type', sa.Enum('BOOST', 'SITUATIONAL', 'PASSIVE', name='traiteffecttype'), nullable=False))
        batch_op.add_column(sa.Column('effect_value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('position_groups', sa.JSON(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traits', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('position_groups')
        batch_op.drop_column('effect_value')
        batch_op.drop_column('effect_type')

    with op.batch_alter_table('player_traits', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('acquired_date')

    with op.batch_alter_table('player_game_starts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_starts_teammates_hash'))
        batch_op.drop_index('idx_player_game')
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('teammates_hash')
        batch_op.drop_column('position_started')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_type',
               existing_type=sa.Enum('REGULAR', 'THANKSGIVING', 'PRIMETIME', 'PLAYOFF', 'SUPER_BOWL', name='gametype'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'REGULAR'"))

    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.alter_column('tier',
               existing_type=sa.Enum('LEGEND', 'ELITE', 'VETERAN', 'DEVELOPING', 'ROOKIE', name='coachtier'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'DEVELOPING'"))

    op.create_table('_alembic_tmp_player',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('position', sa.VARCHAR(), nullable=False),
    sa.Column('height', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.INTEGER(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('team_id', sa.INTEGER(), nullable=True),
    sa.Column('speed', sa.INTEGER(), nullable=False),
    sa.Column('acceleration', sa.INTEGER(), nullable=False),
    sa.Column('strength', sa.INTEGER(), nullable=False),
    sa.Column('agility', sa.INTEGER(), nullable=False),
    sa.Column('awareness', sa.INTEGER(), nullable=False),
    sa.Column('throw_power', sa.INTEGER(), nullable=False),
    sa.Column('throw_accuracy_short', sa.INTEGER(), nullable=False),
    sa.Column('throw_accuracy_mid', sa.INTEGER(), nullable=False),
    sa.Column('throw_accuracy_deep', sa.INTEGER(), nullable=False),
    sa.Column('catching', sa.INTEGER(), nullable=False),
    sa.Column('route_running', sa.INTEGER(), nullable=False),
    sa.Column('pass_block', sa.INTEGER(), nullable=False),
    sa.Column('run_block', sa.INTEGER(), nullable=False),
    sa.Column('tackle', sa.INTEGER(), nullable=False),
    sa.Column('hit_power', sa.INTEGER(), nullable=False),
    sa.Column('block_shed', sa.INTEGER(), nullable=False),
    sa.Column('man_coverage', sa.INTEGER(), nullable=False),
    sa.Column('zone_coverage', sa.INTEGER(), nullable=False),
    sa.Column('pass_rush_power', sa.INTEGER(), nullable=False),
    sa.Column('pass_rush_finesse', sa.INTEGER(), nullable=False),
    sa.Column('kick_power', sa.INTEGER(), nullable=False),
    sa.Column('kick_accuracy', sa.INTEGER(), nullable=False),
    sa.Column('arm_slot', sa.VARCHAR(), nullable=False),
    sa.Column('release_point_height', sa.FLOAT(), nullable=False),
    sa.Column('vision_cone_angle', sa.INTEGER(), nullable=False),
    sa.Column('break_tackle_threshold', sa.FLOAT(), nullable=False),
    sa.Column('xp', sa.INTEGER(), nullable=False),
    sa.Column('level', sa.INTEGER(), nullable=False),
    sa.Column('skill_points', sa.INTEGER(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('nano_id', sa.VARCHAR(), nullable=True),
    sa.Column('experience', sa.INTEGER(), nullable=False),
    sa.Column('jersey_number', sa.INTEGER(), nullable=False),
    sa.Column('overall_rating', sa.INTEGER(), nullable=False),
    sa.Column('contract_years', sa.INTEGER(), nullable=False),
    sa.Column('contract_salary', sa.INTEGER(), nullable=False),
    sa.Column('is_rookie', sa.BOOLEAN(), nullable=False),
    sa.Column('depth_chart_rank', sa.INTEGER(), server_default=sa.text('(999)'), nullable=False),
    sa.Column('college', sa.VARCHAR(), nullable=True),
    sa.Column('stamina', sa.INTEGER(), nullable=False),
    sa.Column('injury_resistance', sa.INTEGER(), nullable=False),
    sa.Column('play_recognition', sa.INTEGER(), nullable=False),
    sa.Column('development_trait', sa.VARCHAR(), nullable=False),
    sa.Column('morale', sa.INTEGER(), nullable=False),
    sa.Column('injury_status', sa.VARCHAR(), nullable=False),
    sa.Column('injury_type', sa.VARCHAR(), nullable=True),
    sa.Column('weeks_to_recovery', sa.INTEGER(), nullable=False),
    sa.Column('is_retired', sa.BOOLEAN(), nullable=False),
    sa.Column('retirement_year', sa.INTEGER(), nullable=True),
    sa.Column('legacy_score', sa.INTEGER(), nullable=False),
    sa.Column('pocket_presence', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('quick_release', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('scramble_willingness', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('throw_on_run', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('patience', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('pass_pro_rating', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('juke_efficiency', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('release', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('blocking_tenacity', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('pull_speed', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('anchor', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('discipline', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('first_step', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('gap_integrity', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('coverage_disguise', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('blitz_timing', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('run_fit', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('press', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('ball_tracking', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('run_support', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('hang_time', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('coffin_corner', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('return_vision', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('injury_severity', sa.INTEGER(), nullable=False),
    sa.Column('injury_recurrence_risk', sa.FLOAT(), nullable=False),
    sa.Column('forty_yard_dash', sa.FLOAT(), nullable=True),
    sa.Column('bench_press', sa.INTEGER(), nullable=True),
    sa.Column('vertical_jump', sa.FLOAT(), nullable=True),
    sa.Column('broad_jump', sa.INTEGER(), nullable=True),
    sa.Column('three_cone_drill', sa.FLOAT(), nullable=True),
    sa.Column('twenty_yard_shuttle', sa.FLOAT(), nullable=True),
    sa.Column('power_clean_max', sa.INTEGER(), nullable=True),
    sa.Column('gps_speed_max', sa.FLOAT(), nullable=True),
    sa.Column('s2_cognition_score', sa.INTEGER(), nullable=True),
    sa.Column('medical_flags', sqlite.JSON(), nullable=True),
    sa.Column('genesis_revealed', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
