"""Add coaching philosophy fields

Revision ID: f153bd84a19f
Revises: b2c3d4e5f6g7
Create Date: 2025-12-14 19:37:54.267392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f153bd84a19f'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6g7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('REGULAR', 'THANKSGIVING', 'PRIMETIME', 'PLAYOFF', 'SUPER_BOWL', name='gametype'),
               nullable=False,
               existing_server_default=sa.text("'REGULAR'"))

    with op.batch_alter_table('player_game_starts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_started', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('teammates_hash', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('idx_player_game', ['player_id', 'game_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_player_game_starts_teammates_hash'), ['teammates_hash'], unique=False)

    with op.batch_alter_table('player_traits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acquired_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('source', sa.Enum('DRAFT', 'DEVELOPMENT', 'MILESTONE', name='traitsource'), nullable=False))

    with op.batch_alter_table('traits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effect_type', sa.Enum('BOOST', 'SITUATIONAL', 'PASSIVE', name='traiteffecttype'), nullable=False))
        batch_op.add_column(sa.Column('effect_value', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('position_groups', sa.JSON(), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traits', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('position_groups')
        batch_op.drop_column('effect_value')
        batch_op.drop_column('effect_type')

    with op.batch_alter_table('player_traits', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('acquired_date')

    with op.batch_alter_table('player_game_starts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_starts_teammates_hash'))
        batch_op.drop_index('idx_player_game')
        batch_op.alter_column('game_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('teammates_hash')
        batch_op.drop_column('position_started')

    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('game_type',
               existing_type=sa.Enum('REGULAR', 'THANKSGIVING', 'PRIMETIME', 'PLAYOFF', 'SUPER_BOWL', name='gametype'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'REGULAR'"))

