"""
Scouting Schemas (AI-Enhanced)
==============================
Pydantic schemas for AI-generated scouting reports and player backstories.

Best Practices Applied:
- Pydantic V2 ConfigDict for model configuration
- Clear field descriptions for schema documentation
- Separate request/response models per FastAPI conventions
"""

from pydantic import BaseModel, ConfigDict, Field


class ScoutingReportAI(BaseModel):
    """
    AI-generated scouting report for a draft prospect.

    Generated by Gemini 2.5 Pro based on player attributes and team context.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "summary": "Elite route runner with exceptional hands and game-breaking speed.",
                "strengths": ["Route running", "Contested catches", "YAC ability"],
                "weaknesses": ["Run blocking", "Physical at the catch point"],
                "nfl_comparison": "Plays like Justin Jefferson - precise routes with explosive ability after the catch",
                "ceiling_projection": "Pro Bowl caliber WR1",
                "floor_projection": "Reliable WR2 with red zone value",
                "draft_grade": "A",
                "fit_analysis": "Would immediately upgrade the passing attack as a true X receiver.",
            }
        }
    )

    summary: str = Field(
        ..., description="2-3 sentence overview of the player's profile and potential"
    )
    strengths: list[str] = Field(
        ..., min_length=2, max_length=6, description="3-5 key strengths that translate to the NFL"
    )
    weaknesses: list[str] = Field(
        ..., min_length=1, max_length=4, description="2-4 areas of concern or development needs"
    )
    nfl_comparison: str = Field(
        ..., description="Comparison to current or former NFL player with similar style"
    )
    ceiling_projection: str = Field(
        ..., description="Best-case scenario development (e.g., 'Pro Bowl caliber')"
    )
    floor_projection: str = Field(
        ..., description="Worst-case scenario development (e.g., 'Quality backup')"
    )
    draft_grade: str = Field(
        ...,
        pattern=r"^[A-F][+-]?$",
        description="Overall draft grade (A+, A, A-, B+, B, B-, C+, C, C-, D, F)",
    )
    fit_analysis: str = Field(
        ..., description="How this player would fit the team's current needs and system"
    )


class PlayerBackstory(BaseModel):
    """
    AI-generated biographical backstory for a player.

    Creates narrative depth through procedurally generated personal details.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "hometown": "Miami, Florida",
                "background": "Born and raised in the Overtown neighborhood of Miami...",
                "personality_traits": ["Competitive", "Team-first mentality", "Quiet leader"],
                "motivations": "Playing for his late grandmother who never missed a game.",
                "notable_college_moments": ["Game-winning catch vs Alabama", "Rose Bowl MVP"],
                "adversity_overcome": "Tore ACL freshman year, came back stronger",
            }
        }
    )

    hometown: str = Field(..., description="Player's hometown (city, state)")
    background: str = Field(..., description="2-3 paragraph biographical background story")
    personality_traits: list[str] = Field(
        ..., min_length=2, max_length=5, description="Key personality characteristics"
    )
    motivations: str = Field(..., description="What drives this player - personal motivation story")
    notable_college_moments: list[str] = Field(
        default_factory=list, description="Memorable college career highlights"
    )
    adversity_overcome: str | None = Field(
        None, description="Challenge or hardship the player has overcome (optional)"
    )


class ScoutingReportRequest(BaseModel):
    """Request body for generating a scouting report."""

    player_id: int
    team_id: int | None = Field(None, description="Team ID to tailor fit analysis (optional)")
    include_backstory: bool = Field(False, description="Also generate player backstory")


class ScoutingReportResponse(BaseModel):
    """Full response including scouting report and optional backstory."""

    model_config = ConfigDict(from_attributes=True)

    player_id: int
    player_name: str
    position: str
    overall_rating: int
    report: ScoutingReportAI
    backstory: PlayerBackstory | None = None
    generated_at: str = Field(..., description="ISO 8601 timestamp of generation")
    cached: bool = Field(False, description="Whether this was retrieved from cache")


class BatchScoutingRequest(BaseModel):
    """Request body for batch generating scouting reports."""

    player_ids: list[int] = Field(
        ..., min_length=1, max_length=50, description="List of player IDs to generate reports for"
    )
    team_id: int | None = None


class BatchScoutingResponse(BaseModel):
    """Response for batch scouting report generation."""

    generated_count: int
    failed_count: int
    player_ids_generated: list[int]
    player_ids_failed: list[int]
