"""Application-wide constants."""

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Season Configuration
DEFAULT_REGULAR_SEASON_WEEKS = 18
DEFAULT_PLAYOFF_WEEKS = 4

# Simulation
DEFAULT_PLAYS_PER_GAME = 100
DEFAULT_PLAY_DELAY_SECONDS = 5.0

# League Leaders
DEFAULT_LEADERS_LIMIT = 5
MAX_LEADERS_LIMIT = 20

# Draft
DEFAULT_DRAFT_ROUNDS = 7
PICKS_PER_ROUND = 32

# Salary Cap
DEFAULT_SALARY_CAP = 200_000_000  # $200M

# Player Ratings
MIN_PLAYER_RATING = 0
MAX_PLAYER_RATING = 100
DEFAULT_PLAYER_RATING = 50

# Database
DEFAULT_DB_POOL_SIZE = 5
DEFAULT_DB_MAX_OVERFLOW = 10
DEFAULT_DB_POOL_TIMEOUT = 30
DEFAULT_DB_POOL_RECYCLE = 3600